// Verbatim from vkpi_v6.15.7_integrated.html


import React from "react";
import { Activity, Camera as Instagram, Key, MessageCircle as Twitter } from "lucide-react";

const e = React.createElement;

export function generateVisualHtml({ language, period, sections }: any) {
  const lang = language || "zh";
  const isWeekly = period === "weekly";
  const today = new Date();
  const dateStr = today.toLocaleDateString(lang === "zh" ? "zh-CN" : "en-US", { year: "numeric", month: "long", day: "numeric" });
  const periodStr = isWeekly 
    ? (lang === "zh" ? "2026 年 5 月 17 日 – 5 月 24 日" : "May 17 – May 24, 2026")
    : (lang === "zh" ? "2026 年 4 月 25 日 – 5 月 24 日" : "Apr 25 – May 24, 2026");
  const reportTitle = lang === "zh" 
    ? `Viltrox 营销${isWeekly ? "周" : "月"}报` 
    : `Viltrox Marketing ${isWeekly ? "Weekly" : "Monthly"} Report`;
  
  // V6.10.4: 周报 / 月报数据
  const m = isWeekly ? {
    rosterDelta: "+3", activeAccounts: 101, prevActive: 87, activeKol: 89, activeMatrix: 12,
    reach: "94.2M", reachKol: "73.8M", reachMatrix: "20.4M", reachPct: "+12.1%",
    er: "4.05%", erDelta: "+0.11%", erKol: "4.32%", erMatrix: "2.95%",
    activeWeekLabel: lang === "zh" ? "本周有发帖" : "Active this week",
    reachLabel: lang === "zh" ? "7 天曝光" : "7-Day Reach",
    deltaPeriod: lang === "zh" ? "本周" : "this week",
  } : {
    rosterDelta: "+12", activeAccounts: 301, prevActive: 273, activeKol: 287, activeMatrix: 14,
    reach: "367.61M", reachKol: "287.61M", reachMatrix: "80.0M", reachPct: "+18.4%",
    er: "3.94%", erDelta: "+0.18%", erKol: "4.21%", erMatrix: "2.87%",
    activeWeekLabel: lang === "zh" ? "30D 有发帖" : "Active in 30D",
    reachLabel: lang === "zh" ? "30 天曝光" : "30-Day Reach",
    deltaPeriod: lang === "zh" ? "本月" : "this month",
  };
  
  const T = lang === "zh" ? {
    kpi: "一、KPI 总览",
    kolVsCompany: "二、公司 vs KOL 详细对比",
    platform: "三、各平台 Deep Dive",
    good: "四、好消息",
    bad: "五、问题与风险",
    sentiment: "六、品牌风评分析",
    contentRecs: "七、内容改进建议",
    events: "八、活动进度",
    attr: "九、归因管线接入进度",
    ai: "十、决策洞察",
    period: "统计周期",
    generated: "生成时间",
    activeRoster: "签约/矩阵总数",
    active30d: "本月有发帖",
    exposure: "30 天累计曝光",
    er: "加权 ER",
    gmv: "归因 GMV",
    roi: "平均 ROI",
    pending: "待接入",
    kol: "KOL",
    company: "公司账号",
    breakdown: "分布",
    topMovers: "Top 5 KOL 贡献(月曝光)",
    upTrend: "30 天 KOL 增长趋势",
    sentimentOverall: "总体情绪(8,247 条评论)",
    positive: "正向",
    neutral: "中性",
    negative: "负向",
    posKeywords: "好评关键词",
    negKeywords: "差评关键词",
    progress: "进度",
    eventList: "近期活动",
    budgetLocked: "已落实预算",
    timelineMilestone: "关键里程碑",
    aiInsight: "今日决策建议(置信度 92%)",
    footer: "由 V-KPI 内部辅助系统自动生成",
  } : {
    kpi: "1. KPI Overview",
    kolVsCompany: "2. Company vs KOL · Detailed Comparison",
    platform: "3. Platform Deep Dive",
    good: "4. Good News",
    bad: "5. Issues & Risks",
    sentiment: "6. Brand Sentiment Analysis",
    contentRecs: "7. Content Recommendations",
    events: "8. Events Progress",
    attr: "9. Attribution Pipeline",
    ai: "10. AI Decision Insights",
    period: "Period",
    generated: "Generated",
    activeRoster: "Active Roster",
    active30d: "Active in 30D",
    exposure: "30D Exposure",
    er: "Weighted ER",
    gmv: "Attributed GMV",
    roi: "Avg ROI",
    pending: "Pending",
    kol: "KOL",
    company: "Company Matrix",
    breakdown: "Breakdown",
    topMovers: "Top 5 KOL Contribution (Monthly Reach)",
    upTrend: "30-Day KOL Roster Growth Trend",
    sentimentOverall: "Overall Sentiment (8,247 comments)",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    posKeywords: "Positive Keywords",
    negKeywords: "Negative Keywords",
    progress: "Progress",
    eventList: "Upcoming Events",
    budgetLocked: "Budget Locked",
    timelineMilestone: "Key Milestone",
    aiInsight: "Today's Recommendation (92% confidence)",
    footer: "Generated by V-KPI Internal Marketing Intelligence",
  };
  
  // V6.10.4: 周报 vs 月报数据
  const rosterData = isWeekly 
    ? [1038,1039,1040,1040,1041,1041,1041]
    : [1013,1015,1017,1018,1020,1022,1024,1025,1027,1029,1030,1032,1033,1034,1035,1036,1037,1038,1039,1040,1040,1040,1041,1041,1041,1041,1041,1041,1041,1041];
  const drawTrendChart = (data: any, color = "#a855f7") => {
    const w = 660, h = 120, pad = 12;
    const min = Math.min(...data), max = Math.max(...data);
    const range = max - min || 1;
    const stepX = (w - pad * 2) / (data.length - 1);
    const pts = data.map((v: any, i: number) => [pad + i * stepX, h - pad - ((v - min) / range) * (h - pad * 2)]);
    const linePath = pts.map((p: any, i: number) => `${i === 0 ? "M" : "L"}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(" ");
    const areaPath = `${linePath} L${pts[pts.length-1][0]},${h-pad} L${pad},${h-pad} Z`;
    return `<svg viewBox="0 0 ${w} ${h}" style="width:100%; height:140px;" preserveAspectRatio="none">
      <defs>
        <linearGradient id="gradTrend" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="${color}" stop-opacity="0.25"/>
          <stop offset="100%" stop-color="${color}" stop-opacity="0"/>
        </linearGradient>
      </defs>
      <path d="${areaPath}" fill="url(#gradTrend)"/>
      <path d="${linePath}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      <circle cx="${pts[pts.length-1][0]}" cy="${pts[pts.length-1][1]}" r="4" fill="${color}"/>
      <text x="${pts[0][0]}" y="${h-2}" font-size="10" fill="#94a3b8">${min}</text>
      <text x="${pts[pts.length-1][0]-30}" y="${pts[pts.length-1][1]-8}" font-size="11" font-weight="600" fill="${color}">${max}</text>
    </svg>`;
  };
  
  // ─ 水平柱状图(Top 5 KOL) ─
  const drawBarChart = (items: any, color = "#a855f7") => {
    const max = Math.max(...items.map((x: any) => x.value));
    return items.map((it: any) => {
      const pct = (it.value / max) * 100;
      return `
      <div style="display:flex; align-items:center; gap:12px; margin-bottom:8px;">
        <div style="width:160px; flex-shrink:0; font-size:12px; font-weight:500; color:#334155;">${it.label}</div>
        <div style="flex:1; height:18px; background:#f1f5f9; border-radius:4px; position:relative; overflow:hidden;">
          <div style="position:absolute; left:0; top:0; bottom:0; width:${pct}%; background:linear-gradient(90deg, ${color}, ${color}aa); border-radius:4px;"></div>
        </div>
        <div style="width:80px; flex-shrink:0; text-align:right; font-size:12px; font-weight:600; color:#1e293b; font-variant-numeric:tabular-nums;">${it.display}</div>
      </div>`;
    }).join("");
  };
  
  // ─ 饼图(SVG donut) ─
  const drawDonut = (segments: any, size = 160) => {
    const cx = size / 2, cy = size / 2, r = size / 2 - 8, inner = r - 22;
    let cumulative = 0;
    const total = segments.reduce((s: any, x: any) => s + x.value, 0);
    const arcs = segments.map((seg: any) => {
      const startAngle = (cumulative / total) * 2 * Math.PI - Math.PI / 2;
      cumulative += seg.value;
      const endAngle = (cumulative / total) * 2 * Math.PI - Math.PI / 2;
      const largeArc = endAngle - startAngle > Math.PI ? 1 : 0;
      const x1 = cx + r * Math.cos(startAngle);
      const y1 = cy + r * Math.sin(startAngle);
      const x2 = cx + r * Math.cos(endAngle);
      const y2 = cy + r * Math.sin(endAngle);
      const xi2 = cx + inner * Math.cos(endAngle);
      const yi2 = cy + inner * Math.sin(endAngle);
      const xi1 = cx + inner * Math.cos(startAngle);
      const yi1 = cy + inner * Math.sin(startAngle);
      return `<path d="M${x1},${y1} A${r},${r} 0 ${largeArc} 1 ${x2},${y2} L${xi2},${yi2} A${inner},${inner} 0 ${largeArc} 0 ${xi1},${yi1} Z" fill="${seg.color}"/>`;
    }).join("");
    return `<svg viewBox="0 0 ${size} ${size}" style="width:${size}px; height:${size}px;">
      ${arcs}
      <circle cx="${cx}" cy="${cy}" r="${inner - 2}" fill="white"/>
    </svg>`;
  };
  
  // V6.10.4: 周报 / 月报数据
  const platformData = isWeekly ? [
    { label: "Instagram",   value: 36.4,  display: "36.4M",  color: "#ec4899" },
    { label: "YouTube",     value: 30.1,  display: "30.1M",  color: "#ef4444" },
    { label: "TikTok",      value: 18.7,  display: "18.7M",  color: "#06b6d4" },
    { label: "Weibo",       value: 5.8,   display: "5.8M",   color: "#f59e0b" },
    { label: "Other",       value: 3.2,   display: "3.2M",   color: "#64748b" },
  ] : [
    { label: "Instagram",   value: 142.3, display: "142.3M", color: "#ec4899" },
    { label: "YouTube",     value: 118.5, display: "118.5M", color: "#ef4444" },
    { label: "TikTok",      value: 72.4,  display: "72.4M",  color: "#06b6d4" },
    { label: "Weibo",       value: 22.1,  display: "22.1M",  color: "#f59e0b" },
    { label: "Other",       value: 12.3,  display: "12.3M",  color: "#64748b" },
  ];
  const topKolData = isWeekly ? [
    { label: "@PeterLindgren",    value: 11.2, display: "11.2M" },
    { label: "@MattiHaapoja",     value: 7.4,  display: "7.4M"  },
    { label: "@DSLRVideoShooter", value: 4.6,  display: "4.6M"  },
    { label: "@TokyoLens",        value: 2.8,  display: "2.8M"  },
    { label: "@PotatoJet",        value: 2.4,  display: "2.4M"  },
  ] : [
    { label: "@PeterLindgren",    value: 38.4, display: "38.4M" },
    { label: "@MattiHaapoja",     value: 24.8, display: "24.8M" },
    { label: "@DSLRVideoShooter", value: 18.2, display: "18.2M" },
    { label: "@PotatoJet",        value: 12.7, display: "12.7M" },
    { label: "@TokyoLens",        value: 9.4,  display: "9.4M"  },
  ];
  const sentimentSegments = [
    { label: T.positive, value: 76.0, color: "#10b981" },
    { label: T.neutral,  value: 16.0, color: "#94a3b8" },
    { label: T.negative, value: 8.0,  color: "#ef4444" },
  ];
  // 关键词数据(取该周期的累积)
  const kwScale = isWeekly ? 0.235 : 1;  // 周报评论量约月报的 23%
  const posKeywords = [
    { w: "sharp",         n: Math.round(488 * kwScale) },
    { w: "color",         n: Math.round(312 * kwScale) },
    { w: "value",         n: Math.round(287 * kwScale) },
    { w: "build quality", n: Math.round(231 * kwScale) },
    { w: "bokeh",         n: Math.round(198 * kwScale) },
    { w: "lightweight",   n: Math.round(167 * kwScale) },
    { w: "weather seal",  n: Math.round(124 * kwScale) },
    { w: "fast aperture", n: Math.round(109 * kwScale) },
  ];
  const negKeywords = [
    { w: "focus hunting", n: Math.round(89 * kwScale) },
    { w: "tripod mount",  n: Math.round(54 * kwScale) },
    { w: "shipping",      n: Math.round(42 * kwScale) },
    { w: "noisy AF motor",n: Math.round(38 * kwScale) },
    { w: "rear filter",   n: Math.round(21 * kwScale) },
    { w: "support",       n: Math.round(18 * kwScale) },
  ];
  
  let html = "";
  
  // ─── 顶部:Header + 标题 ───
  html += `<div class="header">
    <div class="brand">VILTROX</div>
    <h1>${reportTitle}</h1>
    <div class="meta">
      <span><strong>${T.period}:</strong> ${periodStr}</span>
      <span><strong>${T.generated}:</strong> ${dateStr}</span>
    </div>
  </div>`;
  
  // ─── 1. KPI 总览(6 卡 + 双趋势) ───
  if (sections.kpiOverview) {
    html += `<section><h2>${T.kpi}</h2>`;
    html += `<div class="kpi-grid">
      <div class="kpi-card">
        <div class="kpi-label">${T.activeRoster}</div>
        <div class="kpi-value">1,041</div>
        <div class="kpi-delta up">↑ ${m.rosterDelta} ${m.deltaPeriod}</div>
        <div class="kpi-sub">${T.kol} 1,023 · ${T.company} 18</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">${m.activeWeekLabel}</div>
        <div class="kpi-value">${m.activeAccounts}</div>
        <div class="kpi-delta up">↑ +${m.activeAccounts - m.prevActive} vs ${m.prevActive}</div>
        <div class="kpi-sub">${T.kol} ${m.activeKol} · ${T.company} ${m.activeMatrix}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">${m.reachLabel}</div>
        <div class="kpi-value">${m.reach}</div>
        <div class="kpi-delta up">↑ ${m.reachPct}</div>
        <div class="kpi-sub">${T.kol} ${m.reachKol} · ${T.company} ${m.reachMatrix}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">${T.er}</div>
        <div class="kpi-value">${m.er}</div>
        <div class="kpi-delta up">↑ ${m.erDelta}</div>
        <div class="kpi-sub">${T.kol} ${m.erKol} · ${T.company} ${m.erMatrix}</div>
      </div>
      <div class="kpi-card pending">
        <div class="kpi-label">${T.gmv}</div>
        <div class="kpi-value">--</div>
        <div class="kpi-delta pending">⏳ ${T.pending} · 40%</div>
        <div class="kpi-sub">${lang === "zh" ? "待 Shopify 接入" : "Awaiting Shopify"}</div>
      </div>
      <div class="kpi-card pending">
        <div class="kpi-label">${T.roi}</div>
        <div class="kpi-value">--</div>
        <div class="kpi-delta pending">⏳ ${T.pending} · 10%</div>
        <div class="kpi-sub">${lang === "zh" ? "待成本数据" : "Awaiting Cost"}</div>
      </div>
    </div>`;
    
    // Trend
    html += `<div class="card">
      <div class="card-title">${T.upTrend}</div>
      ${drawTrendChart(rosterData)}
    </div>`;
    
    // 平台分布 + Top 5 KOL 并排
    html += `<div class="two-col">
      <div class="card">
        <div class="card-title">${T.exposure} · ${T.platform} ${T.breakdown}</div>
        <div style="display:flex; align-items:center; gap:24px;">
          ${drawDonut(platformData.map(p => ({ ...p })))}
          <div style="flex:1;">
            ${platformData.map(p => `
              <div style="display:flex; align-items:center; gap:8px; margin-bottom:6px; font-size:12px;">
                <span style="width:10px; height:10px; border-radius:2px; background:${p.color};"></span>
                <span style="flex:1; color:#475569;">${p.label}</span>
                <span style="font-weight:600; color:#1e293b;">${p.display}</span>
              </div>`).join("")}
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-title">${T.topMovers}</div>
        ${drawBarChart(topKolData, "#a855f7")}
      </div>
    </div>`;
    html += `</section>`;
  }
  
  // ─── 2. 公司 vs KOL 对比(V6.10.3) ───
  if (sections.kolVsCompany) {
    html += `<section><h2>${T.kolVsCompany}</h2>`;
    
    // 对比卡片 - 两栏并列
    html += `<div class="two-col">
      <div class="card" style="border-left: 4px solid #ec4899;">
        <div class="card-title" style="color: #ec4899;">KOL Roster · 1,023</div>
        <div style="display:grid; grid-template-columns:1fr 1fr; gap:6px; font-size:11px;">
          <div><span style="color:#94a3b8;">${lang === "zh" ? "活跃" : "Active"}:</span> <strong>287 (28.1%)</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "本月发帖" : "Posts"}:</span> <strong>1,124</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "曝光" : "Reach"}:</span> <strong>287.61M</strong></div>
          <div><span style="color:#94a3b8;">ER:</span> <strong style="color:#10b981;">4.21%</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "单账号" : "Per-account"}:</span> <strong>281k</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "单帖" : "Per-post"}:</span> <strong>256k</strong></div>
        </div>
        <div style="margin-top:8px; font-size:10px; color:#64748b;">${lang === "zh" ? "内容偏向" : "Content"}: ${lang === "zh" ? "实战 / 评测 60%" : "Field / reviews 60%"}</div>
      </div>
      <div class="card" style="border-left: 4px solid #06b6d4;">
        <div class="card-title" style="color: #06b6d4;">Company Matrix · 18</div>
        <div style="display:grid; grid-template-columns:1fr 1fr; gap:6px; font-size:11px;">
          <div><span style="color:#94a3b8;">${lang === "zh" ? "活跃" : "Active"}:</span> <strong>14 (77.8%)</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "本月发帖" : "Posts"}:</span> <strong>132</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "曝光" : "Reach"}:</span> <strong>80.0M</strong></div>
          <div><span style="color:#94a3b8;">ER:</span> <strong style="color:#f59e0b;">2.87%</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "单账号" : "Per-account"}:</span> <strong>4.44M</strong></div>
          <div><span style="color:#94a3b8;">${lang === "zh" ? "单帖" : "Per-post"}:</span> <strong>606k</strong></div>
        </div>
        <div style="margin-top:8px; font-size:10px; color:#64748b;">${lang === "zh" ? "内容偏向" : "Content"}: ${lang === "zh" ? "产品 demo 70%" : "Product demo 70%"}</div>
      </div>
    </div>`;
    
    // 效率对比柱状图
    html += `<div class="card">
      <div class="card-title">${lang === "zh" ? "效率对比(矩阵单账号倍数)" : "Efficiency Comparison (Matrix multiplier per account)"}</div>
      ${drawBarChart([
        { label: lang === "zh" ? "单账号月曝光" : "Per-account monthly reach", value: 15.8, display: "15.8x" },
        { label: lang === "zh" ? "单帖平均曝光" : "Per-post avg reach",         value: 2.4,  display: "2.4x" },
        { label: lang === "zh" ? "活跃率" : "Activity rate",                    value: 2.8,  display: "2.8x" },
        { label: lang === "zh" ? "ER(KOL 更高)" : "ER (KOL higher)",          value: 0.68, display: "0.68x · KOL +47%" },
      ], "#a855f7")}
    </div>`;
    
    // 定位建议卡片
    html += `<div class="two-col">
      <div class="card" style="background:linear-gradient(135deg, #fdf2f8, #fff); border-color:#fbcfe8;">
        <div class="card-title" style="color:#ec4899;">${lang === "zh" ? "🎬 KOL 应聚焦" : "🎬 KOL Focus"}</div>
        <ul style="margin:6px 0 0; padding-left:16px; font-size:11px; color:#475569;">
          <li>${lang === "zh" ? "实战使用场景" : "Field use cases"}</li>
          <li>${lang === "zh" ? "个人创作风格融入" : "Personal creative integration"}</li>
          <li>${lang === "zh" ? "真实评测 + 对比" : "Authentic reviews + comparisons"}</li>
        </ul>
      </div>
      <div class="card" style="background:linear-gradient(135deg, #ecfeff, #fff); border-color:#a5f3fc;">
        <div class="card-title" style="color:#06b6d4;">${lang === "zh" ? "🏢 矩阵应聚焦" : "🏢 Matrix Focus"}</div>
        <ul style="margin:6px 0 0; padding-left:16px; font-size:11px; color:#475569;">
          <li>${lang === "zh" ? "产品教育 / 技术解读" : "Product education / tech deep-dives"}</li>
          <li>${lang === "zh" ? "工程师 BTS / 实验室视角" : "Engineer BTS / lab perspective"}</li>
          <li>${lang === "zh" ? "官方政策更新 / 权威发声" : "Official updates / authoritative voice"}</li>
        </ul>
      </div>
    </div>`;
    
    html += `<div class="callout">
      <strong>${lang === "zh" ? "关键洞察" : "Key Insight"}:</strong> 
      ${lang === "zh" 
        ? "KOL Top 20%(~205 个)贡献 80% 曝光,矩阵 18 个账号已触顶。建议矩阵账号定位「权威 + 教育」,KOL 定位「真实 + 多样」,并形成「创作 + 工程」协同。" 
        : "Top 20% of KOLs (~205 accounts) drive 80% of impressions; 18 matrix accounts have hit ceiling. Position matrix as 'authority + education,' KOL as 'authenticity + diversity,' and form a 'creator + engineer' content synergy."}
    </div>`;
    html += `</section>`;
  }
  
  // ─── 3. 平台 Deep Dive(V6.10.3) ───
  if (sections.platformDeepDive) {
    html += `<section><h2>${T.platform}</h2>`;
    
    const platforms = lang === "zh" ? [
      { name: "Instagram", emoji: "📷", color: "#ec4899", kol: 487, matrix: 9, reach: "142.3M", er: "4.18%",
        types: [{ label: "Reels", er: 5.84 }, { label: "Posts", er: 4.12 }, { label: "Stories", er: 1.94 }],
        rec: "Reels 占比 23% → 60% · 减少 Stories", urgent: false },
      { name: "YouTube", emoji: "📺", color: "#ef4444", kol: 312, matrix: 7, reach: "118.5M", er: "4.05%",
        types: [{ label: "Shorts", er: 6.21 }, { label: "8-15min", er: 4.92 }, { label: "15min+", er: 2.78 }],
        rec: "中视频 8-15min 主推 · Shorts 12% → 30%", urgent: false },
      { name: "TikTok", emoji: "🎵", color: "#06b6d4", kol: 142, matrix: 0, reach: "72.4M", er: "3.84%",
        types: [{ label: "<60s", er: 4.92 }, { label: "1-3min", er: 3.21 }],
        rec: "🚨 紧急建矩阵账号 · Hook 前 3 秒必有产品", urgent: true },
      { name: "Weibo", emoji: "💬", color: "#f59e0b", kol: 64, matrix: 2, reach: "22.1M", er: "2.91%",
        types: [{ label: "话题营销", er: 4.66 }, { label: "评测", er: 2.91 }, { label: "抽奖", er: 4.65 }],
        rec: "加大话题营销 + 月度抽奖活动", urgent: false },
      { name: "Bilibili", emoji: "📹", color: "#22d3ee", kol: 36, matrix: 0, reach: "12.3M", er: "4.21%",
        types: [{ label: "深度评测", er: 5.2 }, { label: "教学", er: 4.1 }, { label: "对比", er: 4.8 }],
        rec: "🚨 建立 1 个工程师视角矩阵账号", urgent: true },
    ] : [
      { name: "Instagram", emoji: "📷", color: "#ec4899", kol: 487, matrix: 9, reach: "142.3M", er: "4.18%",
        types: [{ label: "Reels", er: 5.84 }, { label: "Posts", er: 4.12 }, { label: "Stories", er: 1.94 }],
        rec: "Reels 23% → 60% · Reduce Stories", urgent: false },
      { name: "YouTube", emoji: "📺", color: "#ef4444", kol: 312, matrix: 7, reach: "118.5M", er: "4.05%",
        types: [{ label: "Shorts", er: 6.21 }, { label: "8-15min", er: 4.92 }, { label: "15min+", er: 2.78 }],
        rec: "Push 8-15min mid-form · Shorts 12% → 30%", urgent: false },
      { name: "TikTok", emoji: "🎵", color: "#06b6d4", kol: 142, matrix: 0, reach: "72.4M", er: "3.84%",
        types: [{ label: "<60s", er: 4.92 }, { label: "1-3min", er: 3.21 }],
        rec: "🚨 URGENT: launch matrix · 3s hook show product", urgent: true },
      { name: "Weibo", emoji: "💬", color: "#f59e0b", kol: 64, matrix: 2, reach: "22.1M", er: "2.91%",
        types: [{ label: "Topic Mkt", er: 4.66 }, { label: "Review", er: 2.91 }, { label: "Giveaway", er: 4.65 }],
        rec: "Increase topic marketing + monthly giveaways", urgent: false },
      { name: "Bilibili", emoji: "📹", color: "#22d3ee", kol: 36, matrix: 0, reach: "12.3M", er: "4.21%",
        types: [{ label: "Deep review", er: 5.2 }, { label: "Tutorial", er: 4.1 }, { label: "Comparison", er: 4.8 }],
        rec: "🚨 Launch 1 engineer-POV matrix account", urgent: true },
    ];
    
    html += `<div class="platform-grid">`;
    platforms.forEach(p => {
      const maxEr = Math.max(...p.types.map(t => t.er));
      html += `
      <div class="platform-card" style="${p.urgent ? "border-color:#ef4444; background:linear-gradient(135deg, #fef2f2, #fff);" : ""}">
        <div class="platform-head" style="border-bottom-color: ${p.color};">
          <span class="platform-emoji">${p.emoji}</span>
          <span class="platform-name" style="color: ${p.color};">${p.name}</span>
          <span class="platform-er">ER ${p.er}</span>
        </div>
        <div class="platform-stats">
          <div><span class="ps-label">KOL:</span> <strong>${p.kol}</strong></div>
          <div><span class="ps-label">${lang === "zh" ? "矩阵" : "Matrix"}:</span> <strong${p.matrix === 0 ? ' style="color:#ef4444;"' : ""}>${p.matrix}${p.matrix === 0 ? " ⚠️" : ""}</strong></div>
          <div><span class="ps-label">${lang === "zh" ? "曝光" : "Reach"}:</span> <strong>${p.reach}</strong></div>
        </div>
        <div class="platform-types">
          <div class="ps-sublabel">${lang === "zh" ? "内容类型 ER" : "Content Type ER"}</div>
          ${p.types.map(t => `
            <div class="platform-type-row">
              <span class="pt-label">${t.label}</span>
              <div class="pt-bar"><div class="pt-fill" style="width:${(t.er/7*100).toFixed(0)}%; background:${p.color};"></div></div>
              <span class="pt-value">${t.er}%</span>
            </div>`).join("")}
        </div>
        <div class="platform-rec${p.urgent ? " urgent" : ""}">
          📈 ${p.rec}
        </div>
      </div>`;
    });
    html += `</div></section>`;
  }
  
  // ─── 4. 好消息 ───
  if (sections.goodNews) {
    html += `<section><h2>${T.good}</h2>`;
    html += `<div class="news-list good">`;
    const goodItems = lang === "zh" ? [
      { tag: "Top 1", text: "<strong>@PeterLindgren</strong>(YT 1.42M)+12.4k follower,贡献 +38.4M 曝光,135mm LAB 评测驱动本周 47.2% Shopify 转化" },
      { tag: "ER 王", text: "<strong>@MattiHaapoja</strong> YouTube ER 8.7%(团队最高),本月发文 15 次(+66.7% vs 上月 9)" },
      { tag: "矩阵", text: "<strong>Viltrox Cinema</strong> +8.4k follower,ER 4.84%(矩阵最高)" },
      { tag: "品牌", text: "VILTROX 品牌提及 24h 内 +127%(基线 543/天 → 1,233/天)" },
      { tag: "活动", text: "<strong>CineGear LA 2026</strong> 物料 78% 完成(18/22),预算 $124k/$185k 落实(67%)" },
    ] : [
      { tag: "Top 1", text: "<strong>@PeterLindgren</strong> (YT 1.42M) +12.4k followers, +38.4M impressions; 135mm LAB review drove 47.2% of weekly Shopify conversions" },
      { tag: "Top ER", text: "<strong>@MattiHaapoja</strong> YouTube ER 8.7% (team highest); 15 posts this month (+66.7% vs 9 prior)" },
      { tag: "Matrix", text: "<strong>Viltrox Cinema</strong> +8.4k followers, ER 4.84% (highest in matrix)" },
      { tag: "Brand", text: "VILTROX mentions surged +127% in 24h (baseline 543/day → 1,233/day)" },
      { tag: "Event", text: "<strong>CineGear LA 2026</strong> 78% material complete (18/22); $124k/$185k budget locked (67%)" },
    ];
    html += goodItems.map(it => `
      <div class="news-item good">
        <span class="news-tag good">${it.tag}</span>
        <span class="news-text">${it.text}</span>
      </div>`).join("");
    html += `</div></section>`;
  }
  
  // ─── 5. 坏消息 ───
  if (sections.badNews) {
    html += `<section><h2>${T.bad}</h2>`;
    html += `<div class="news-list bad">`;
    const badItems = lang === "zh" ? [
      { tag: "流失", text: "<strong>@CineEule</strong>(YT)-340 follower(89.2k → 88.86k),ER 1.2%(roster 最低),前次合作 ROI &lt; 0.5x,建议评估" },
      { tag: "沉默", text: "<strong>740 KOL 沉默</strong>(占 roster 72.3%):60+ 天 234 个 / 30–60 天 312 个 / 14–30 天 194 个" },
      { tag: "竞品", text: "Sony 发布 <strong>FE 85mm F1.4 GM II</strong>(5/20)— 直接对标 Viltrox AF 85mm F1.4 PRO,$1,798 vs $499" },
      { tag: "竞品", text: "Sigma 56mm F1.4 DG DN 套装 B&H 折扣 -$80(5/22 起)— 影响 56mm 销售" },
      { tag: "阻塞", text: "GMV 归因卡在 Shopify webhook 密钥轮转,阻塞 5 步管线中第 3、4、5 步" },
      { tag: "阻塞", text: "成本数据仍在 Google Sheets,无法自动入库,导致 ROI 暂时无法计算" },
    ] : [
      { tag: "Loss", text: "<strong>@CineEule</strong> (YT) -340 followers (89.2k → 88.86k); ER 1.2% (lowest in roster); previous campaign ROI &lt; 0.5x; recommend partnership review" },
      { tag: "Silent", text: "<strong>740 silent KOLs</strong> (72.3% of roster): 60+ days 234 / 30–60 days 312 / 14–30 days 194" },
      { tag: "Competitor", text: "Sony released <strong>FE 85mm F1.4 GM II</strong> (May 20) — direct rival to AF 85mm F1.4 PRO; $1,798 vs $499" },
      { tag: "Competitor", text: "Sigma 56mm F1.4 DG DN bundle discounted -$80 at B&H (May 22) — affects our 56mm sales" },
      { tag: "Blocker", text: "GMV attribution blocked on Shopify webhook key rotation; blocking steps 3–5 of 5" },
      { tag: "Blocker", text: "Cost data still in Google Sheets, no auto-ingestion, ROI cannot compute" },
    ];
    html += badItems.map(it => `
      <div class="news-item bad">
        <span class="news-tag bad">${it.tag}</span>
        <span class="news-text">${it.text}</span>
      </div>`).join("");
    html += `</div></section>`;
  }
  
  // ─── 6. 风评分析 ───
  if (sections.brandSentiment) {
    html += `<section><h2>${T.sentiment}</h2>`;
    // 情绪饼图 + 关键词词云
    html += `<div class="two-col">
      <div class="card">
        <div class="card-title">${T.sentimentOverall}</div>
        <div style="display:flex; align-items:center; gap:20px;">
          ${drawDonut(sentimentSegments, 140)}
          <div style="flex:1;">
            ${sentimentSegments.map(s => `
              <div style="margin-bottom:10px;">
                <div style="display:flex; align-items:center; justify-content:space-between; margin-bottom:2px;">
                  <span style="display:flex; align-items:center; gap:6px; font-size:12px; color:#475569;">
                    <span style="width:10px; height:10px; border-radius:2px; background:${s.color};"></span>
                    ${s.label}
                  </span>
                  <span style="font-size:13px; font-weight:600; color:#1e293b;">${s.value}%</span>
                </div>
                <div style="height:4px; background:#f1f5f9; border-radius:2px; overflow:hidden;">
                  <div style="height:100%; width:${s.value}%; background:${s.color};"></div>
                </div>
              </div>`).join("")}
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-title">${T.posKeywords}</div>
        <div class="keyword-cloud good">
          ${posKeywords.map(k => `
            <span class="kw" style="font-size:${10 + (k.n / 50)}px; opacity:${0.5 + (k.n / 500)};">${k.w}<sub>${k.n}</sub></span>
          `).join("")}
        </div>
        <div class="card-title" style="margin-top:14px;">${T.negKeywords}</div>
        <div class="keyword-cloud bad">
          ${negKeywords.map(k => `
            <span class="kw bad" style="font-size:${10 + (k.n / 12)}px; opacity:${0.5 + (k.n / 90)};">${k.w}<sub>${k.n}</sub></span>
          `).join("")}
        </div>
      </div>
    </div>`;
    
    // 平台 sentiment 表
    html += `<div class="card">
      <div class="card-title">${lang === "zh" ? "分平台情绪分布" : "Per-Platform Sentiment"}</div>
      <table>
        <tr><th>${T.platform}</th><th>${lang === "zh" ? "评论总数" : "Comments"}</th><th>${T.positive}</th><th>${T.neutral}</th><th>${T.negative}</th><th>Comment ER</th></tr>
        <tr><td>Instagram</td><td>4,021</td><td class="pos">78.2%</td><td>14.8%</td><td class="neg">7.0%</td><td>0.282%</td></tr>
        <tr><td>YouTube</td><td>2,876</td><td class="pos">74.1%</td><td>16.9%</td><td class="neg">9.0%</td><td>0.243%</td></tr>
        <tr><td>TikTok</td><td>892</td><td class="pos">76.5%</td><td>17.4%</td><td class="neg">6.1%</td><td>0.123%</td></tr>
        <tr><td>Weibo</td><td>458</td><td class="pos">71.2%</td><td>19.7%</td><td class="neg">9.1%</td><td>0.207%</td></tr>
      </table>
    </div>`;
    
    // 产品满意度
    html += `<div class="card">
      <div class="card-title">${lang === "zh" ? "产品满意度(基于评论关键词聚合)" : "Product Satisfaction (Keyword-aggregated)"}</div>
      ${drawBarChart([
        { label: "135mm LAB",           value: 4.8, display: "⭐ 4.8 (1,234)" },
        { label: "AF 56mm F1.4 Pro",    value: 4.7, display: "⭐ 4.7 (892)" },
        { label: "AF 85mm F1.4 Pro",    value: 4.7, display: "⭐ 4.7 (786)" },
        { label: "AF 75mm F1.2",        value: 4.3, display: "⭐ 4.3 (412)" },
        { label: "Cine 27mm T2.0",      value: 4.9, display: "⭐ 4.9 (187)" },
      ], "#f59e0b")}
    </div>`;
    html += `</section>`;
  }
  
  // ─── 7. 内容改进建议(V6.10.3) ───
  if (sections.contentRecs) {
    html += `<section><h2>${T.contentRecs}</h2>`;
    
    // 高表现 vs 低表现 内容
    const highPerf = lang === "zh" ? [
      { name: "实战拍摄 + 设备评测",   er: 6.24, vs: "+58%", note: "最高表现 · KOL 主力" },
      { name: "产品 vs 竞品对比",      er: 5.81, vs: "+47%", note: "用户决策类内容" },
      { name: "BTS / Day-in-the-life", er: 5.40, vs: "+37%", note: "真实感,KOL 优势" },
      { name: "Reels / Shorts (60s)",  er: 5.21, vs: "+32%", note: "算法偏好,各平台" },
      { name: "工程师/产品经理视角",   er: 4.92, vs: "+25%", note: "矩阵机会(预估)" },
    ] : [
      { name: "Field shoot + review",         er: 6.24, vs: "+58%", note: "Top performer · KOL-led" },
      { name: "Product vs competitor",        er: 5.81, vs: "+47%", note: "Decision-stage content" },
      { name: "BTS / Day-in-the-life",        er: 5.40, vs: "+37%", note: "Authentic · KOL strength" },
      { name: "Reels / Shorts (<60s)",        er: 5.21, vs: "+32%", note: "Algorithm-favored" },
      { name: "Engineer / PM perspective",    er: 4.92, vs: "+25%", note: "Matrix opportunity (est.)" },
    ];
    
    const lowPerf = lang === "zh" ? [
      { name: "纯产品 demo / 开箱",     er: 2.10, vs: "-47%", note: "加入使用场景叙事" },
      { name: "长篇硬广告",             er: 1.81, vs: "-54%", note: "转为软植入" },
      { name: "Instagram Stories",      er: 1.94, vs: "-51%", note: "减少 / 转 Reels" },
      { name: "矩阵通用产品介绍",       er: 2.87, vs: "-27%", note: "加入工程师视角" },
      { name: "YouTube 长视频 15min+",  er: 2.78, vs: "-29%", note: "8-15min 中视频更好" },
    ] : [
      { name: "Pure product demo / unboxing", er: 2.10, vs: "-47%", note: "Add use-case narrative" },
      { name: "Long-form hard ads",           er: 1.81, vs: "-54%", note: "Pivot to soft placement" },
      { name: "Instagram Stories",            er: 1.94, vs: "-51%", note: "Reduce / convert to Reels" },
      { name: "Matrix generic product intro", er: 2.87, vs: "-27%", note: "Add engineer perspective" },
      { name: "YouTube long-form 15min+",     er: 2.78, vs: "-29%", note: "Mid-form 8-15min wins" },
    ];
    
    html += `<div class="two-col">
      <div class="card" style="background:linear-gradient(135deg, #f0fdf4, #fff); border-color:#bbf7d0;">
        <div class="card-title" style="color:#10b981;">${lang === "zh" ? "✅ 高表现内容(模仿)" : "✅ High-Performance (Replicate)"}</div>
        ${highPerf.map(p => `
          <div class="perf-row good">
            <span class="perf-name">${p.name}</span>
            <span class="perf-er good">ER ${p.er}%</span>
            <span class="perf-vs good">${p.vs}</span>
          </div>
          <div class="perf-note">${p.note}</div>
        `).join("")}
      </div>
      <div class="card" style="background:linear-gradient(135deg, #fef2f2, #fff); border-color:#fecaca;">
        <div class="card-title" style="color:#ef4444;">${lang === "zh" ? "⚠️ 低表现内容(改进)" : "⚠️ Low-Performance (Improve)"}</div>
        ${lowPerf.map(p => `
          <div class="perf-row bad">
            <span class="perf-name">${p.name}</span>
            <span class="perf-er bad">ER ${p.er}%</span>
            <span class="perf-vs bad">${p.vs}</span>
          </div>
          <div class="perf-note">${p.note}</div>
        `).join("")}
      </div>
    </div>`;
    
    // 具体建议清单
    const actions = lang === "zh" ? [
      { num: "1", text: "<strong>内容形式优先级</strong>: Reels/Shorts > 中视频(8-15min) > 静态 Posts > Stories" },
      { num: "2", text: "<strong>主题排序</strong>: 实战 > 评测 > 对比 > 教程 > 硬广(减少硬广 35% → 10%)" },
      { num: "3", text: "<strong>矩阵账号大改造</strong>: 增加「工程师视角」内容(目前 0%)· 减少通用产品介绍 50%" },
      { num: "4", text: "<strong>多平台联动</strong>: 同步发文(IG + YT + TT)ER 比单平台高 35%" },
      { num: "5", text: "<strong>市场机会</strong>: 加大 FPV 无人机内容(行业 ER 7.8% vs 我们 3.94%)· 配合 AF 16mm F1.4" },
    ] : [
      { num: "1", text: "<strong>Format priority</strong>: Reels/Shorts > Mid-form (8-15min) > Static Posts > Stories" },
      { num: "2", text: "<strong>Theme ranking</strong>: Field > Reviews > Comparisons > Tutorials > Hard ads (cut 35% → 10%)" },
      { num: "3", text: "<strong>Matrix overhaul</strong>: Add 'engineer POV' (currently 0%) · cut generic intros 50%" },
      { num: "4", text: "<strong>Cross-platform sync</strong>: IG+YT+TT same content yields 35% higher ER" },
      { num: "5", text: "<strong>Market opportunity</strong>: Push FPV drone content (industry ER 7.8% vs ours 3.94%) · pair with AF 16mm F1.4" },
    ];
    
    html += `<div class="card">
      <div class="card-title">${lang === "zh" ? "📋 具体改进建议(可执行)" : "📋 Specific Actions (Executable)"}</div>
      <div class="action-list">
        ${actions.map(a => `
          <div class="action-row">
            <span class="action-num">${a.num}</span>
            <span class="action-text">${a.text}</span>
          </div>`).join("")}
      </div>
    </div>`;
    
    // 内容缺位提醒
    html += `<div class="callout" style="border-left-color:#ef4444; background:#fef2f2; color:#7f1d1d;">
      <strong>${lang === "zh" ? "🚨 内容缺位(优先处理):" : "🚨 Content Gaps (Address Soon):"}</strong>
      ${lang === "zh" 
        ? "矩阵账号在 <strong>TikTok / Bilibili 完全缺位</strong>(Q3 各建 1 个)· \"工程师 BTS\" 系列在所有平台缺位(评论提及 67 次)· 国内长视频(B 站)市场未触达(KOL 36 个但矩阵 0)" 
        : "Matrix absent on <strong>TikTok / Bilibili</strong> (launch 1 each in Q3) · 'Engineer BTS' series missing across all platforms (mentioned 67× in comments) · Mainland long-form (Bilibili) market untouched (36 KOL but 0 matrix)"}
    </div>`;
    
    html += `</section>`;
  }
  
  // ─── 8. 活动进度 ───
  if (sections.eventsProgress) {
    html += `<section><h2>${T.events}</h2>`;
    const evts = lang === "zh" ? [
      { name: "CineGear LA 2026",      date: "6/13–15",  loc: "LA Convention Center #4520", pct: 78, budget: "$124k / $185k", milestone: "已确认 4 名 KOL on-site", status: "🟢" },
      { name: "SCAD Spring Workshop",  date: "6/22–24",  loc: "Savannah, SCAD Film",          pct: 45, budget: "$14k / $28k",   milestone: "学生报名 67/100",         status: "🟡" },
      { name: "Tokyo Creator Meetup",  date: "7/8",      loc: "Tokyo Shibuya",                pct: 90, budget: "$22k / $25k",   milestone: "@TokyoLens 主持已确认",   status: "🟢" },
      { name: "Photokina Cologne",     date: "9/18–21",  loc: "Cologne Messe",                pct: 22, budget: "$28k / $120k",  milestone: "展位申请审批中",          status: "🟡" },
    ] : [
      { name: "CineGear LA 2026",      date: "6/13–15",  loc: "LA Convention Center #4520", pct: 78, budget: "$124k / $185k", milestone: "4 KOLs confirmed on-site",  status: "🟢" },
      { name: "SCAD Spring Workshop",  date: "6/22–24",  loc: "Savannah, SCAD Film",          pct: 45, budget: "$14k / $28k",   milestone: "Student signups 67/100",     status: "🟡" },
      { name: "Tokyo Creator Meetup",  date: "7/8",      loc: "Tokyo Shibuya",                pct: 90, budget: "$22k / $25k",   milestone: "@TokyoLens host confirmed",  status: "🟢" },
      { name: "Photokina Cologne",     date: "9/18–21",  loc: "Cologne Messe",                pct: 22, budget: "$28k / $120k",  milestone: "Booth application pending",  status: "🟡" },
    ];
    html += `<div class="event-list">`;
    html += evts.map(ev => `
      <div class="event-card">
        <div class="event-head">
          <span class="event-status">${ev.status}</span>
          <span class="event-name">${ev.name}</span>
          <span class="event-date">${ev.date}</span>
        </div>
        <div class="event-meta">${ev.loc} · ${T.timelineMilestone}: ${ev.milestone}</div>
        <div class="event-progress-row">
          <div class="event-progress-bar">
            <div class="event-progress-fill" style="width:${ev.pct}%; background:${ev.pct >= 70 ? "#10b981" : ev.pct >= 40 ? "#f59e0b" : "#94a3b8"};"></div>
          </div>
          <div class="event-progress-text">${ev.pct}%</div>
          <div class="event-budget">${T.budgetLocked}: <strong>${ev.budget}</strong></div>
        </div>
      </div>`).join("");
    html += `</div>`;
    html += `<div class="callout">
      <strong>${lang === "zh" ? "预算总览" : "Budget Summary"}:</strong> 
      ${lang === "zh" ? "已承诺 $358k · 已落实 $188k (52.5%) · 余 $170k" : "Committed $358k · Locked $188k (52.5%) · Remaining $170k"}
    </div>`;
    html += `</section>`;
  }
  
  // ─── 9. Attribution Pipeline ───
  if (sections.attribution) {
    html += `<section><h2>${T.attr}</h2>`;
    const steps = lang === "zh" ? [
      { step: "Shopify Webhook 注册",     status: "done",         desc: "API key + endpoint registered",   owner: "Engineering", date: "5/12" },
      { step: "订单同步",                 status: "in-progress",  desc: "回填过去 90 天订单",             owner: "Tom Liu",     date: "5/22" },
      { step: "UTM 标记",                 status: "in-progress",  desc: "VIA-{handle}-10 折扣码已上线 47 个", owner: "Maya Wong", date: "5/24" },
      { step: "归因逻辑",                 status: "pending",      desc: "UTM + cookie 匹配订单到 KOL",     owner: "Engineering", date: "6/1 ETA" },
      { step: "仪表板展示",               status: "pending",      desc: "KPI strip + drilldown",          owner: "Engineering", date: "6/5 ETA" },
    ] : [
      { step: "Shopify Webhook",         status: "done",         desc: "API key + endpoint registered",  owner: "Engineering", date: "May 12" },
      { step: "Order Sync",              status: "in-progress",  desc: "Backfilling 90 days of orders",  owner: "Tom Liu",     date: "May 22" },
      { step: "UTM Tagging",             status: "in-progress",  desc: "47 VIA-{handle}-10 codes live",  owner: "Maya Wong",   date: "May 24" },
      { step: "Attribution Logic",       status: "pending",      desc: "Match orders to KOL via UTM",    owner: "Engineering", date: "Jun 1 ETA" },
      { step: "Dashboard Display",       status: "pending",      desc: "KPI strip + drilldown",          owner: "Engineering", date: "Jun 5 ETA" },
    ];
    html += `<div class="pipeline-title">${lang === "zh" ? "归因 GMV · 40% 完成 · ETA 6 月 5 日" : "Attributed GMV · 40% complete · ETA Jun 5, 2026"}</div>`;
    html += `<div class="pipeline">`;
    steps.forEach((s, i) => {
      const dotColor = s.status === "done" ? "#10b981" : s.status === "in-progress" ? "#f59e0b" : "#94a3b8";
      const fill = s.status === "done";
      html += `
      <div class="pipeline-row">
        <div class="pipeline-dot" style="${fill ? `background:${dotColor};` : ""} border-color:${dotColor};"></div>
        <div class="pipeline-content">
          <div class="pipeline-head">
            <span class="pipeline-step">${s.step}</span>
            <span class="pipeline-badge" style="color:${dotColor}; background:${dotColor}1a;">
              ${s.status === "done" ? (lang === "zh" ? "完成" : "Done") : s.status === "in-progress" ? (lang === "zh" ? "进行中" : "In Progress") : (lang === "zh" ? "待开发" : "Pending")}
            </span>
            <span class="pipeline-date">${s.date}</span>
          </div>
          <div class="pipeline-desc">${s.desc}</div>
          <div class="pipeline-owner">👤 ${s.owner}</div>
        </div>
      </div>`;
    });
    html += `</div></section>`;
  }
  
  // ─── 10. AI Insights ───
  if (sections.aiInsights) {
    html += `<section><h2>${T.ai}</h2>`;
    html += `<div class="ai-callout">
      <div class="ai-confidence">${T.aiInsight}</div>
      <div class="ai-body">${
        lang === "zh"
          ? "135mm LAB 营销活动整体表现优于平均 23%。@PeterLindgren 评测视频驱动本周 47.2% 转化(基于 VIA-peter-10 折扣码使用追踪)。<br><br><strong>建议:</strong> 增加 $50k 预算扩展 @PeterLindgren 后续内容(2 条 longform + 4 条 short)。"
          : "135mm LAB campaign performing 23% above average. @PeterLindgren's review drove 47.2% of weekly conversions (tracked via VIA-peter-10 code). <br><br><strong>Recommendation:</strong> Allocate additional $50k to extend @PeterLindgren content (2 longform + 4 shorts)."
      }</div>
    </div>`;
    html += `<div class="ai-grid">
      <div class="ai-item">
        <div class="ai-item-h">${lang === "zh" ? "🔥 热门话题" : "🔥 Trending"}</div>
        <div>#CineGear2025 ${lang === "zh" ? "在 Twitter/IG 增长" : "surging on Twitter/IG"} <strong>+212%</strong> ${lang === "zh" ? "过去 7 天" : "past 7 days"}</div>
      </div>
      <div class="ai-item">
        <div class="ai-item-h">${lang === "zh" ? "💡 市场机会" : "💡 Opportunity"}</div>
        <div>${lang === "zh" ? "FPV 无人机内容 ER" : "FPV drone content ER"} <strong>7.8%</strong>(2.0x ${lang === "zh" ? "均值" : "vs mean"} 3.94%)— AF 16mm F1.4 ${lang === "zh" ? "适配" : "fits"}</div>
      </div>
      <div class="ai-item">
        <div class="ai-item-h">${lang === "zh" ? "⚠️ 风险" : "⚠️ Risk"}</div>
        <div>Sony FE 85mm GM II ${lang === "zh" ? "对 AF 85mm Pro 影响待观察 · 建议 7 日内做对比" : "impact on AF 85mm Pro pending · recommend comparison content in 7 days"}</div>
      </div>
    </div>`;
    html += `</section>`;
  }
  
  // Footer
  html += `<div class="footer">${T.footer} · ${dateStr}</div>`;
  
  return html;
}
