from __future__ import annotations

import ast
import copy
import hashlib
import inspect
import json
from pathlib import Path
from typing import Any

import pytest

from app.platform.models import evaluation_artifact, readiness
from app.platform.models.readiness import assess_model_readiness
from scripts.vkpi_engineering_health_collect import collect_complexity
from tests.model_evidence_signing import public_key_b64, sign_probe_evidence
from tests.test_model_readiness_evidence_gate import (
    AS_OF,
    EVALUATION_KEY_ID,
    EVALUATION_PRIVATE_KEY,
    EVALUATION_PUBLIC_KEYS,
    PROBE_KEY_ID,
    PROBE_PRIVATE_KEY,
    PROBE_PUBLIC_KEYS,
    _evidence,
    _rebind_and_resign_probe,
    _resign_artifact,
    _resolved,
)


# These are SHA-256 digests of the complete canonical return dictionaries from
# the pre-split implementation at this exact reviewed revision.  The matrix was
# generated by executing that implementation and the split implementation over
# cloned inputs and asserting direct dictionary equality before freezing hashes.
LEGACY_READINESS_REVISION = "7c2c5837af71092a29b989b66d7b3d34dc3e4740"
LEGACY_FULL_RETURN_SHA256 = {
    "all_quality_failures": "c72a10b7e9489dce0678e1cf950f65346c9e5df34557ed14e09dff8fc2b05c76",
    "configured_empty": "3a1d226b46f651103d0a2625bd1ae821557cabe195ddcdc1e65ec86fc04bd696",
    "empty_artifact": "8636e3e95ceaccda890773ea70953b9ab9799ccef2620a630d7dc36ae58f38da",
    "future_dataset": "44fdce8e334ce1a334ca7aa7060c2099e2d62c930b884e8585d3b6773d2bfbba",
    "malformed_samples_bool": "07976c12dff98af5d5fe50c04751a247c94deaca011a2a9d8c511eaaed24fbb4",
    "model_revision_mismatch": "23da23127830ac1a5e49daf998b5935cbf32b6c543f78f27241f0494d48b0a2c",
    "naive_probe_time": "44cfd8dd5acb4efe534919f0701193e90883d078fb95da5a6d55227aa1ecbfb8",
    "non_mapping_root": "3a1d226b46f651103d0a2625bd1ae821557cabe195ddcdc1e65ec86fc04bd696",
    "probe_only": "a0b460f4c57c7aa536d591e4c7e8bd0238fbde9f1d0a031004a06567c1a4ddc9",
    "probe_unsupported_field": "7a6083ecebf0cfe6c8b1b25ac830bf8f67cc6db3f40f9a75034124f1a382354b",
    "registered_only": "d3def21195ed8cff46d914a04d0b77947c821f87c3a1b088157f9c07f67695cb",
    "same_signer": "407e1a843bc4c054435cb0d4f26eb20fbff7501b6b8a5443addea8ca7bc6448b",
    "sample_29": "3c92f7f765022fd22e64c9f3af7882328c61985d71fba1f7a3864912233f1902",
    "sample_30": "0e5caf5c3ffd5ec7680a7701ec6ff3e966f6696677943f91efbb725deb42ccb5",
    "sample_missing_field": "3f8115468217a1a435742ee7bc96e50b25481d69ce8bacc7075c2205ec75276e",
    "stale_dataset": "1ee14b0e4b5bccaebeae32410a6d458ee3a663273b72698f77ba1d2900a0e928",
    "tampered_summary": "836f3a427f29623b704f2622c079ef53a2362e8b418bda9c94d98f81841f5358",
    "task_29_of_60": "91c9333db23286a3f5a37149714e1d91002017b27c2ac8bbe94c47976b811a42",
}


@pytest.fixture(autouse=True)
def _trusted_characterization_keys(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        evaluation_artifact,
        "TRUSTED_EVALUATION_ED25519_PUBLIC_KEYS",
        dict(EVALUATION_PUBLIC_KEYS),
    )
    monkeypatch.setattr(
        readiness,
        "TRUSTED_EXACT_PROBE_ED25519_PUBLIC_KEYS",
        dict(PROBE_PUBLIC_KEYS),
    )


def _digest(value: dict[str, Any]) -> str:
    payload = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _case(
    name: str,
    *,
    configured: bool = True,
    evidence: Any = None,
    expected_tasks: tuple[str, ...] | None = None,
    probe_keys: dict[str, str] | None = None,
) -> tuple[str, dict[str, Any], dict[str, str] | None]:
    return (
        name,
        {
            "configured": configured,
            "evidence": evidence,
            "expected_tasks": expected_tasks,
            "as_of": AS_OF,
        },
        probe_keys,
    )


def _full_return_cases() -> list[tuple[str, dict[str, Any], dict[str, str] | None]]:
    cases = [
        _case("registered_only", configured=False),
        _case("configured_empty"),
    ]

    probe_only = _evidence()
    probe_only.pop("evaluation")
    cases.append(_case("probe_only", evidence=probe_only))
    cases.extend(
        (
            _case("sample_29", evidence=_evidence(samples=29)),
            _case("sample_30", evidence=_evidence(samples=30)),
            _case(
                "task_29_of_60",
                evidence=_evidence(
                    samples=60,
                    tasks=("first",) * 31 + ("second",) * 29,
                ),
                expected_tasks=("first", "second"),
            ),
            _case(
                "all_quality_failures",
                evidence=_evidence(
                    samples=30,
                    successes=27,
                    structured=27,
                    factual=27,
                    source=27,
                    safety=27,
                    latency_ms=20_000,
                ),
            ),
        )
    )

    stale_dataset = _evidence()
    stale_artifact = stale_dataset["evaluation"]["artifact"]
    stale_artifact["dataset"]["as_of"] = "2025-01-01T00:00:00Z"
    stale_dataset["evaluation"]["artifact"] = _resign_artifact(stale_artifact)
    _rebind_and_resign_probe(stale_dataset)
    cases.append(_case("stale_dataset", evidence=stale_dataset))

    future_dataset = _evidence()
    future_artifact = future_dataset["evaluation"]["artifact"]
    future_artifact["dataset"]["as_of"] = "2026-07-14T12:00:00Z"
    future_dataset["evaluation"]["artifact"] = _resign_artifact(future_artifact)
    _rebind_and_resign_probe(future_dataset)
    cases.append(_case("future_dataset", evidence=future_dataset))
    cases.append(
        _case(
            "model_revision_mismatch",
            evidence=_evidence(model_version="some-other-model"),
        )
    )

    tampered = _evidence()
    tampered["evaluation"]["artifact"]["summary"]["sample_count"] = 999
    cases.append(_case("tampered_summary", evidence=tampered))
    malformed = _evidence()
    malformed["evaluation"]["artifact"]["samples"] = True
    cases.append(_case("malformed_samples_bool", evidence=malformed))

    naive_probe_time = _evidence()
    naive_probe_time["probe"]["as_of"] = "2026-07-13T12:00:00"
    _rebind_and_resign_probe(naive_probe_time)
    cases.append(_case("naive_probe_time", evidence=naive_probe_time))

    unsupported_probe = _evidence()
    unsupported_probe["probe"]["future_claim"] = "x"
    unsupported_probe["probe"] = sign_probe_evidence(
        unsupported_probe["probe"],
        private_key=PROBE_PRIVATE_KEY,
        key_id=PROBE_KEY_ID,
    )
    cases.append(_case("probe_unsupported_field", evidence=unsupported_probe))
    cases.extend(
        (
            _case("non_mapping_root", evidence=["x"]),
            _case(
                "empty_artifact",
                evidence={"probe": {}, "evaluation": {"artifact": {}}},
            ),
        )
    )

    missing_field = _evidence()
    missing_artifact = missing_field["evaluation"]["artifact"]
    missing_artifact["samples"][0].pop("factual_passed")
    missing_field["evaluation"]["artifact"] = _resign_artifact(missing_artifact)
    _rebind_and_resign_probe(missing_field)
    cases.append(_case("sample_missing_field", evidence=missing_field))

    same_signer = _evidence(samples=30)
    same_signer["probe"] = sign_probe_evidence(
        same_signer["probe"],
        private_key=EVALUATION_PRIVATE_KEY,
        key_id=EVALUATION_KEY_ID,
    )
    cases.append(
        _case(
            "same_signer",
            evidence=same_signer,
            probe_keys={
                EVALUATION_KEY_ID: public_key_b64(EVALUATION_PRIVATE_KEY)
            },
        )
    )
    return cases


def test_split_matches_legacy_complete_return_matrix(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    observed: dict[str, str] = {}
    for name, kwargs, probe_keys in _full_return_cases():
        monkeypatch.setattr(
            readiness,
            "TRUSTED_EXACT_PROBE_ED25519_PUBLIC_KEYS",
            dict(probe_keys or PROBE_PUBLIC_KEYS),
        )
        observed[name] = _digest(
            assess_model_readiness(_resolved(), **copy.deepcopy(kwargs))
        )

    assert observed == LEGACY_FULL_RETURN_SHA256
    assert len(observed) == 18


@pytest.mark.parametrize(
    ("dependency_check", "expected_sha256"),
    [
        (
            {
                "valid": False,
                "failure_reasons": ["frozen_dependency_failure"],
                "summary": {},
                "dataset": {},
                "task_sample_counts": {},
            },
            "f7aee07bb9a1235199e39bcf10006d3dd539a842f68575339f245dc8c7c89bb1",
        ),
        (
            {
                "valid": False,
                "failure_reasons": ["frozen_dependency_failure"],
                "summary": {
                    "sample_count": float("inf"),
                    "success_count": float("nan"),
                    "structured_valid_count": -1,
                    "factual_valid_count": True,
                    "source_valid_count": 1.5,
                    "safety_valid_count": "bad",
                    "model_version": "",
                    "failure_reasons": {"bad": "shape"},
                    "latency_ms": {
                        "p50": float("nan"),
                        "p95": float("inf"),
                        "p99": -1,
                    },
                },
                "dataset": {"version": "", "sha256": "", "as_of": None},
                "task_sample_counts": {
                    "ok": 1,
                    "bool": True,
                    "negative": -1,
                    "float": 2.0,
                },
                "attestation_verified": False,
            },
            "fb96a3ef3f1ff79a8b43eefc43e3f974098e04a6cde59bc3d6de4562896ec222",
        ),
    ],
)
def test_missing_and_nonfinite_dependency_projection_matches_legacy(
    monkeypatch: pytest.MonkeyPatch,
    dependency_check: dict[str, Any],
    expected_sha256: str,
) -> None:
    monkeypatch.setattr(
        readiness,
        "verify_model_evaluation_artifact",
        lambda *_args, **_kwargs: copy.deepcopy(dependency_check),
    )
    result = assess_model_readiness(
        _resolved(),
        configured=True,
        evidence={"probe": {}, "evaluation": {"artifact": {"sentinel": 1}}},
        expected_tasks=("task-a",),
        as_of=AS_OF,
    )

    assert _digest(result) == expected_sha256
    assert result["claim_status"] == "descriptive_only"
    assert result["production_ready"] is False
    assert all(
        not isinstance(value, float) or (value == value and abs(value) != float("inf"))
        for value in (
            result["evaluation"]["sample_count"],
            *result["evaluation"]["latency_ms"].values(),
        )
    )


def test_readiness_split_complexity_signature_size_and_leaf_dependency() -> None:
    root = Path(__file__).resolve().parents[1]
    module_paths = (
        root / "backend/app/platform/models/readiness.py",
        root / "backend/app/platform/models/readiness_assessment.py",
    )
    trees = {
        str(path.relative_to(root)): ast.parse(path.read_text(encoding="utf-8"))
        for path in module_paths
    }
    rows = collect_complexity(trees)
    public = next(
        row
        for row in rows
        if row.path.endswith("readiness.py")
        and row.qualified_name == "assess_model_readiness"
    )

    assert public.cc <= 30
    assert max(row.cc for row in rows) <= 30
    assert all(
        len(path.read_text(encoding="utf-8").splitlines()) <= 800
        for path in module_paths
    )
    assert list(inspect.signature(assess_model_readiness).parameters) == [
        "resolved",
        "configured",
        "evidence",
        "expected_tasks",
        "as_of",
        "thresholds",
    ]

    leaf = trees["backend/app/platform/models/readiness_assessment.py"]
    imported_modules = {
        alias.name
        for node in leaf.body
        if isinstance(node, ast.Import)
        for alias in node.names
    } | {
        node.module or ""
        for node in leaf.body
        if isinstance(node, ast.ImportFrom)
    }
    assert not any(name == "app" or name.startswith("app.") for name in imported_modules)
