"""合同模板登记处(2026-06-12 施工,法务文本逐字冻结)。

三份公司模板(0529 版)原文照录,空槽以 [[key]] 标记;LLM 只润色不碰本体(裁令)。
模板正文改动须留痕(git)——这是法务红线,见 docs/contract-generator-spec.md。
"""
from __future__ import annotations

from typing import Any

PARTY_A_ENTITY = "SHENZHEN VILTROX TECHNOLOGY CO., LTD."

# slot type: text / multiline / choice(options) / date / number
# group 用于前端分组渲染;required 缺省 False(留空渲染为下划线)
TEMPLATES: dict[str, dict[str, Any]] = {
    "exchange": {
        "label": "置换合作协议(产品换内容)",
        "title": "PRODUCT-EXCHANGE Creator COLLABORATION AGREEMENT",
        "slots": [
            {"key": "party_b_name", "label": "对方姓名/法名 (Creator)", "group": "对方信息", "required": True},
            {"key": "party_b_address", "label": "对方地址 (Address)", "group": "对方信息"},
            {"key": "party_b_email", "label": "对方邮箱 (Email)", "group": "对方信息"},
            {"key": "party_b_phone", "label": "对方电话 (Phone)", "group": "对方信息"},
            {"key": "product_models", "label": "产品型号 (Product Models)", "group": "产品", "required": True},
            {"key": "quantity", "label": "数量 (Quantity)", "group": "产品", "required": True},
            {"key": "ownership", "label": "归属 (Ownership)", "group": "产品", "type": "choice", "options": ["Permanent (Gift)", "Loaner (Return Required)"], "required": True},
            {"key": "platform", "label": "发布平台 (Platform)", "group": "交付", "required": True},
            {"key": "content_format", "label": "内容形式 (Format)", "group": "交付", "type": "choice", "options": ["Photo", "Video", "Story"], "required": True},
            {"key": "posts_count", "label": "发布条数 (Number of Posts)", "group": "交付", "required": True},
            {"key": "delivery_days", "label": "到货后交付天数 (Delivery Days)", "group": "时间", "type": "choice", "options": ["7 days", "14 days", "30 days"], "required": True},
        ],
        "sections": [
            ("h1", "PRODUCT-EXCHANGE Creator COLLABORATION AGREEMENT"),
            ("h2", "1. Parties"),
            ("p", "Party A (Company): SHENZHEN VILTROX TECHNOLOGY CO., LTD."),
            ("p", "Party B (Creator): [[party_b_name]]"),
            ("p", "Address: [[party_b_address]]"),
            ("p", "Email: [[party_b_email]]"),
            ("p", "Phone: [[party_b_phone]]"),
            ("h2", "2. Purpose"),
            ("p", "Party A agrees to provide Viltrox product(s) in exchange for content created and delivered by Party B. The Creator retains ownership of the original content, and grants the Company the usage rights described in this Agreement. This collaboration does not involve monetary payment unless separately agreed."),
            ("h2", "3. Product(s) Provided"),
            ("p", "Product Model(s): [[product_models]]"),
            ("p", "Quantity: [[quantity]]"),
            ("p", "Ownership: [[ownership]]"),
            ("p", "*If marked as Permanent Gift, ownership transfers to Party B only after the agreed deliverables are completed and any embargo/confidentiality obligations are satisfied."),
            ("h2", "4. Content Deliverables (Required)"),
            ("p", "Party B agrees to publish the following content:"),
            ("li", "Platform: [[platform]]"),
            ("li", "Content Format: [[content_format]]"),
            ("li", "Number of Posts: [[posts_count]]"),
            ("li", "Required Taggings: @Viltrox"),
            ("li", "Required Hashtags: #Viltrox"),
            ("li", "Mention of provided product must be clear and accurate."),
            ("h2", "5. Delivery Deadline"),
            ("p", "Party B agrees to deliver the required content within: [[delivery_days]] of product arrival. Party B must share the content with Party A for preview before or on the posting date."),
            ("h2", "6. Content Usage Rights"),
            ("p", "Party B grants Party A a non-exclusive, worldwide, royalty-free right to repost and use the delivered content on Viltrox-owned organic channels, including social media, website, email, product pages, PR materials, and internal presentations, with reasonable credit where practical. Paid advertising, whitelisting, dark posts, or third-party retailer advertising shall require separate written approval."),
            ("h2", "7. Quality Requirements"),
            ("p", "Content must:"),
            ("li", "Clearly show or demonstrate the Viltrox product(s)"),
            ("li", "Have clean, high-quality visuals (1080p+ for video / 300dpi for images)"),
            ("li", "Avoid incomplete, unusable, or materially below-brief content."),
            ("li", "Be original and created specifically for this collaboration"),
            ("h2", "8. Restrictions"),
            ("p", "Party B agrees NOT to:"),
            ("li", "Misrepresent product performance"),
            ("li", "Promote competing products as the primary focus within the same collaboration post, unless the Parties have agreed to a comparison format in writing."),
            ("li", "Leak unreleased product information"),
            ("li", "Transfer or resell the product if designated as a loaner"),
            ("h2", "9. Failure to Deliver"),
            ("p", "If the Creator materially fails to deliver after a reasonable cure period, the Company may cancel the undelivered portion, request return of any loaner products, and/or request return of the gifted product if such product was provided specifically for the undelivered collaboration."),
            ("h2", "10. Confidentiality & Product Sample Control Clause"),
            ("p", "Definition of Confidential Information: “Confidential Information” shall include, without limitation, any non-public information disclosed by the Company to the Creator, including but not limited to product specifications, technical data, designs, functions, firmware, prototypes, test samples, pricing, launch schedules, marketing plans, business strategies, and any other information not publicly released, whether disclosed in written, oral, visual, electronic, or physical form."),
            ("p", "Confidentiality Obligation: Prior to the official public launch and without prior written consent of the Company, the Creator shall not disclose, publish, distribute, provide, or otherwise make available any Confidential Information to any third party, including but not limited to disclosure through: social media platforms (including but not limited to YouTube, Instagram, TikTok, X, Facebook, Reddit, Discord); blogs, forums, press outlets, private groups, or direct messages; any form of offline display, lending, or sharing."),
            ("p", "No Early Exposure: The Creator shall not engage in any form of early exposure before receiving written authorization from the Company, including but not limited to: posting product images, videos, packaging, test results, or sample footage; teasing, hinting, or implying any upcoming product release; publishing behind-the-scenes content, leaks, or preview-style content."),
            ("p", "No Resale, Transfer, or Commercial Disposal: Product samples are provided strictly for testing and content creation purposes only. The Creator shall not: resell, lease, mortgage, or commercially dispose of the sample; gift, exchange, or transfer the product to any third party; use the product as a giveaway prize, reward, second-hand sale, or any form of transaction."),
            ("p", "No Disassembly or Reverse Engineering: Without prior written consent, the Creator shall not: disassemble, deconstruct, or damage the product sample; conduct reverse engineering, structural analysis, or circuit inspection; extract, modify, or tamper with any software, firmware, or internal parameters."),
            ("h2", "11. Governing Law"),
            ("p", "This Agreement is governed by the laws of the People's Republic of China (excluding HK/Macao/Taiwan)."),
            ("h2", "Signatures"),
            ("p", "Party A: SHENZHEN VILTROX TECHNOLOGY CO., LTD."),
            ("p", "Authorized Representative:   Signature: ____________________  Date: ____________________"),
            ("p", "Party B: [[party_b_name]]"),
            ("p", "Name / Legal Entity:  Signature: ____________________  Date: ____________________"),
        ],
    },
    "paid": {
        "label": "付费合作协议(内容创作计划)",
        "title": "PAID CONTENT CREATION PROGRAM AGREEMENT",
        "slots": [
            {"key": "party_b_name", "label": "对方姓名/法名 (Participant)", "group": "对方信息", "required": True},
            {"key": "product", "label": "产品 (Product)", "group": "产品", "required": True},
            {"key": "campaign_fee", "label": "合作费用 (Campaign Fee / Amount)", "group": "商务", "required": True},
            {"key": "payment_method", "label": "付款方式 (Payment Method)", "group": "商务", "required": True},
            {"key": "deliverable_due_date", "label": "交付截止 (Deliverable Due Date)", "group": "时间", "type": "date", "required": True},
            {"key": "posting_date", "label": "发布/解禁日 (Posting / Embargo Date)", "group": "时间", "type": "date"},
            {"key": "affiliate_link", "label": "联盟链接/折扣码 (Affiliate / Discount Code)", "group": "商务"},
            {"key": "account_name", "label": "收款户名 (Account Name)", "group": "收款信息"},
            {"key": "account_address", "label": "收款人地址 (Address)", "group": "收款信息"},
            {"key": "iban", "label": "IBAN / 账号 (IBAN / Account Number)", "group": "收款信息"},
            {"key": "swift", "label": "Swift / 行号 (Swift Code / Bank Code)", "group": "收款信息"},
            {"key": "bank_name", "label": "银行名称 (Bank Name)", "group": "收款信息"},
            {"key": "bank_address", "label": "银行地址 (Bank Address)", "group": "收款信息"},
            {"key": "content_req_a", "label": "内容要求 a (Content Requirement a)", "group": "交付", "type": "multiline", "required": True},
            {"key": "content_req_b", "label": "内容要求 b", "group": "交付", "type": "multiline"},
            {"key": "content_req_c", "label": "内容要求 c", "group": "交付", "type": "multiline"},
            {"key": "submission_no_later_than", "label": "最迟提交日 (No Later Than)", "group": "时间", "type": "date"},
        ],
        "sections": [
            ("h1", "PAID CONTENT CREATION PROGRAM AGREEMENT"),
            ("p", "Party A: SHENZHEN VILTROX TECHNOLOGY CO., LTD."),
            ("p", "Party B: [[party_b_name]]"),
            ("h2", "Agreement Introduction"),
            ("p", "This Viltrox Content Creation Program Agreement (“Agreement”) is entered into by SHENZHEN VILTROX TECHNOLOGY CO., LTD. (“Company” or “Viltrox”) and [[party_b_name]] (“Participant”). Viltrox is a trademark of the Company. The products involved in this Program are all Viltrox-brand products."),
            ("p", "By entering into this Agreement, the Participant agrees to join the Content Creation Program and provide videos/images to the Company in exchange for the Company's Product(s) and Payment. The Participant retains ownership of the original content, and grants the Company the usage rights described in this Agreement."),
            ("h2", "1. Content Creation Plan"),
            ("p", "In consideration of the Product(s) and support provided by the Company, the Participant agrees to feature, test, demonstrate, or introduce the Company’s Product(s) in the agreed content."),
            ("h2", "2. Product(s) and Payment Provision"),
            ("p", "The Product(s)/Payment(s) offered by the Company include:"),
            ("li", "Product: [[product]]"),
            ("li", "Campaign Fee / Amount: [[campaign_fee]]"),
            ("li", "Payment Method: [[payment_method]]"),
            ("li", "Deliverable Due Date: [[deliverable_due_date]]"),
            ("li", "Posting Date / Embargo Date: [[posting_date]]"),
            ("li", "Affiliate Link / Discount Code: [[affiliate_link]]"),
            ("p", "Payment Information:"),
            ("li", "Account Name: [[account_name]]"),
            ("li", "Address: [[account_address]]"),
            ("li", "IBAN / Account Number: [[iban]]"),
            ("li", "Swift Code / Bank Code: [[swift]]"),
            ("li", "Bank Name: [[bank_name]]"),
            ("li", "Bank Address: [[bank_address]]"),
            ("p", "The Company shall issue payment according to the payment schedule agreed by both Parties. Unless otherwise agreed, payment shall be issued within seven (7) working days after the Company receives the completed deliverables and the required payment information."),
            ("h2", "3. Video/Image Content Requirement"),
            ("p", "The Participant agrees to examine and assemble the Product properly, read and follow all instructions before testing, and provide agreed content. Content Requirements:"),
            ("li", "a) [[content_req_a]]"),
            ("li", "b) [[content_req_b]]"),
            ("li", "c) [[content_req_c]]"),
            ("h2", "4. Content Usage Rights"),
            ("p", "Party B grants Party A a non-exclusive, worldwide, royalty-free right to repost and use the delivered content on Viltrox-owned organic channels, including social media, website, email, product pages, PR materials, and internal presentations, with reasonable credit where practical. Paid advertising, whitelisting, dark posts, or third-party retailer advertising shall require separate written approval."),
            ("h2", "5. Video/Image Submission Requirement"),
            ("p", "1) The videos/images produced shall be shared with the Company for preview before going online."),
            ("p", "2) The videos/images must be delivered within 30 days of product arrival, no later than [[submission_no_later_than]]"),
            ("h2", "6. Shipment, Product Delivery, Payment and Customs Duties"),
            ("p", "1) The Company shall cover all shipment & delivery fees from factory to the Participant."),
            ("p", "2) The Company shall provide accurate and commercially reasonable shipping documents. Where legally appropriate, the Product(s) may be marked as sponsored review/testing samples."),
            ("h2", "7. Special Statement"),
            ("p", "If the Participant is unable to deliver the agreed content on time, the Participant shall notify the Company as soon as reasonably possible. The Parties may agree on a revised timeline. If the Participant materially fails to deliver after a reasonable cure period, the Company may cancel the undelivered portion, request return of loaner products, and/or request a reasonable pro-rata refund for undelivered work."),
            ("h2", "8. Confidentiality & Product Sample Control Clause"),
            ("p", "Definition of Confidential Information: “Confidential Information” shall include, without limitation, any non-public information disclosed by the Company to the Participant, including but not limited to product specifications, technical data, designs, functions, firmware, prototypes, test samples, pricing, launch schedules, marketing plans, business strategies, and any other information not publicly released, whether disclosed in written, oral, visual, electronic, or physical form."),
            ("p", "Confidentiality Obligation: Prior to the official public launch and without prior written consent of the Company, the Participant shall not disclose, publish, distribute, provide, or otherwise make available any Confidential Information to any third party, including but not limited to disclosure through: social media platforms (including but not limited to YouTube, Instagram, TikTok, X, Facebook, Reddit, Discord); blogs, forums, press outlets, private groups, or direct messages; any form of offline display, lending, or sharing."),
            ("p", "No Early Exposure: The Participant shall not engage in any form of early exposure before receiving written authorization from the Company, including but not limited to: posting product images, videos, packaging, test results, or sample footage; teasing, hinting, or implying any upcoming product release; publishing behind-the-scenes content, leaks, or preview-style content."),
            ("p", "No Resale, Transfer, or Commercial Disposal: Product samples are provided strictly for testing and content creation purposes only. The Participant shall not: resell, lease, mortgage, or commercially dispose of the sample; gift, exchange, or transfer the product to any third party; use the product as a giveaway prize, reward, second-hand sale, or any form of transaction."),
            ("p", "No Disassembly or Reverse Engineering: Without prior written consent, the Participant shall not: disassemble, deconstruct, or damage the product sample; conduct reverse engineering, structural analysis, or circuit inspection; extract, modify, or tamper with any software, firmware, or internal parameters."),
            ("p", "Breach & Liability: Any violation of this clause shall constitute a material breach. The Company shall have the right to: immediately terminate the cooperation; require immediate removal of all related content; demand return of the sample and may seek appropriate remedies permitted by law, including removal of unauthorized content, return of samples, and compensation for proven direct losses caused by the breach."),
            ("h2", "9. Force Majeure"),
            ("p", "Neither party shall be liable for breach due to Force Majeure. The affected party must notify the other within three (3) working days and provide proof."),
            ("h2", "10. Governing Law and Dispute Resolution"),
            ("p", "This Agreement is governed by the laws of the People’s Republic of China (excluding HK/Macao/Taiwan). Disputes shall be submitted to Shenzhen Court of International Arbitration (SCIA)."),
            ("h2", "Signatures"),
            ("p", "Party A: SHENZHEN VILTROX TECHNOLOGY CO., LTD."),
            ("p", "Authorized Representative:   Signature: ____________________  Date: ____________________"),
            ("p", "Party B: [[party_b_name]]"),
            ("p", "Name / Legal Entity:  Signature: ____________________  Date: ____________________"),
        ],
    },
    "event": {
        "label": "红人线下活动合作合同",
        "title": "VILTROX OFFLINE EVENT COLLABORATION AGREEMENT",
        "slots": [
            {"key": "party_a_address", "label": "我方地址 (Party A Address)", "group": "我方信息"},
            {"key": "party_b_name", "label": "对方姓名 (Creator / Instructor)", "group": "对方信息", "required": True},
            {"key": "party_b_address", "label": "对方地址 (Address)", "group": "对方信息"},
            {"key": "party_b_email", "label": "对方邮箱 (Email)", "group": "对方信息"},
            {"key": "party_b_phone", "label": "对方电话 (Phone)", "group": "对方信息"},
            {"key": "event_name", "label": "活动名称 (Event Name)", "group": "活动", "required": True},
            {"key": "event_type", "label": "活动类型 (Workshop / Photo Walk / Seminar / Other)", "group": "活动", "required": True},
            {"key": "event_location", "label": "活动地点 (Location)", "group": "活动", "required": True},
            {"key": "event_dates", "label": "活动日期 (Date(s))", "group": "时间", "required": True},
            {"key": "duration", "label": "时长 (Duration)", "group": "时间"},
            {"key": "expected_participants", "label": "预计人数 (Expected Participants)", "group": "活动"},
            {"key": "onsite_instruction", "label": "现场授课/主持 (On-site instruction)", "group": "交付"},
            {"key": "demo_shooting", "label": "演示拍摄/产品展示 (Demo shooting)", "group": "交付"},
            {"key": "pre_event_materials", "label": "会前准备材料 (Pre-event materials)", "group": "交付"},
            {"key": "post_event_deliverables", "label": "会后交付物 (Post-event deliverables)", "group": "交付", "type": "multiline"},
            {"key": "payment_usd", "label": "酬金 USD (Monetary Payment)", "group": "商务"},
            {"key": "payment_schedule", "label": "付款节奏 (Payment Schedule)", "group": "商务"},
            {"key": "travel_terms", "label": "差旅条款 (Travel & Accommodation)", "group": "商务", "type": "multiline"},
            {"key": "provided_products", "label": "提供产品 (Provided Products)", "group": "产品"},
            {"key": "ownership", "label": "归属 (Ownership)", "group": "产品", "type": "choice", "options": ["Loaner", "Gift"]},
        ],
        "sections": [
            ("h1", "VILTROX OFFLINE EVENT COLLABORATION AGREEMENT"),
            ("h2", "This Agreement"),
            ("p", "This Offline Event Collaboration Agreement (“Agreement”) is entered into on the date of signature below by and between:"),
            ("p", "Party A (Company): SHENZHEN VILTROX TECHNOLOGY CO., LTD."),
            ("p", "Address: [[party_a_address]]"),
            ("p", "Party B (Creator / Instructor): [[party_b_name]]"),
            ("p", "Address: [[party_b_address]]"),
            ("p", "Email: [[party_b_email]]"),
            ("p", "Phone: [[party_b_phone]]"),
            ("h2", "1. Project Overview"),
            ("li", "Event Name: [[event_name]]"),
            ("li", "Event Type (Workshop / Photo Walk / Seminar / Other): [[event_type]]"),
            ("li", "Event Location: [[event_location]]"),
            ("li", "Event Date(s): [[event_dates]]"),
            ("li", "Duration: [[duration]]"),
            ("li", "Expected Participants: [[expected_participants]]"),
            ("h2", "2. Deliverables"),
            ("p", "1. On-site instruction / hosting: [[onsite_instruction]]"),
            ("p", "2. Demo shooting / product showcasing: [[demo_shooting]]"),
            ("p", "3. Pre-event preparation materials: [[pre_event_materials]]"),
            ("p", "4. Post-event deliverables: [[post_event_deliverables]]"),
            ("h2", "3. Compensation"),
            ("p", "Monetary Payment: USD [[payment_usd]]"),
            ("p", "Payment Schedule: [[payment_schedule]]"),
            ("p", "Travel & Accommodation: [[travel_terms]]"),
            ("p", "Product Sponsorship: Provided Products: [[provided_products]]"),
            ("p", "Ownership: [[ownership]]"),
            ("h2", "4. Event Requirements"),
            ("p", "Party B agrees to attend punctually, deliver professional content, use Viltrox products when applicable, and maintain professional conduct at all times."),
            ("h2", "5. Content Usage Rights"),
            ("p", "Party B grants Party A perpetual, worldwide, royalty-free usage rights for marketing, social media, advertising, and promotional purposes. Proper credit will be given unless mutually waived."),
            ("h2", "6. Cancellation & Rescheduling"),
            ("p", "6.1 Cancellation by Party B: Must notify Party A immediately. 6.2 Cancellation by Party A: Rescheduling or reimbursement of reasonable expenses. 6.3 Force Majeure applies to both parties."),
            ("h2", "7. Confidentiality"),
            ("p", "Party B shall keep all confidential information private unless disclosure is legally required."),
            ("h2", "8. Conduct & Representation"),
            ("p", "Party B agrees not to defame Viltrox, must notify the Company of any product malfunction, and must avoid promoting competitor products unless agreed."),
            ("h2", "9. Governing Law & Dispute Resolution"),
            ("p", "This Agreement is governed by PRC law and disputes shall be handled by the Shenzhen Court of International Arbitration (SCIA)."),
            ("h2", "10. Entire Agreement"),
            ("p", "This Agreement represents the full understanding between Parties and may only be amended in writing."),
            ("h2", "Signatures"),
            ("p", "Party A: SHENZHEN VILTROX TECHNOLOGY CO., LTD."),
            ("p", "Representative Signature: __________________________  Name & Title: _____________________________________  Date: __________________________"),
            ("p", "Party B (Creator / Instructor): [[party_b_name]]"),
            ("p", "Signature: __________________________  Name: _____________________________________  Date: __________________________"),
        ],
    },
}


def template_catalog() -> dict[str, Any]:
    """供前端表单渲染的模板目录(不含正文,正文只在生成时落档)。"""
    return {
        "party_a": PARTY_A_ENTITY,
        "templates": [
            {
                "key": key,
                "label": value["label"],
                "title": value["title"],
                "slots": value["slots"],
            }
            for key, value in TEMPLATES.items()
        ],
    }
