-- V-KPI Industry Data monitored accounts.
CREATE TABLE IF NOT EXISTS vkpi_industry_accounts (
    id BIGSERIAL PRIMARY KEY,
    account_uid TEXT NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES vkpi_industry_projects(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    platform_user_id TEXT DEFAULT '',
    handle TEXT NOT NULL,
    display_name TEXT DEFAULT '',
    avatar_url TEXT DEFAULT '',
    profile_url TEXT DEFAULT '',
    bio TEXT DEFAULT '',
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    brand_group TEXT DEFAULT '',
    account_role TEXT NOT NULL DEFAULT 'reference',
    region TEXT DEFAULT '',
    category TEXT DEFAULT '',
    linked_kol_pool_id BIGINT REFERENCES vkpi_kol_pool(id) ON DELETE SET NULL,
    auto_kol_link BOOLEAN NOT NULL DEFAULT FALSE,
    crawl_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    crawl_frequency TEXT NOT NULL DEFAULT 'daily',
    last_crawled_at TIMESTAMPTZ,
    last_successful_at TIMESTAMPTZ,
    crawl_error_count INTEGER NOT NULL DEFAULT 0,
    sync_status TEXT NOT NULL DEFAULT 'not_configured',
    notes TEXT DEFAULT '',
    added_by_staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    raw_platform_data TEXT NOT NULL DEFAULT '{}',
    discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(project_id, platform, handle)
);
