-- V-KPI Industry Data account snapshots. YouTube KPI columns are reserved for the finished adapter.
CREATE TABLE IF NOT EXISTS vkpi_industry_account_snapshots (
    id BIGSERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES vkpi_industry_accounts(id) ON DELETE CASCADE,
    snapshot_date DATE NOT NULL,
    followers BIGINT,
    followers_growth_24h BIGINT,
    followers_growth_30d BIGINT,
    followers_growth_pct_30d NUMERIC(10,4),
    posts BIGINT,
    posts_30d BIGINT,
    avg_posts_per_day NUMERIC(10,4),
    views BIGINT,
    views_30d BIGINT,
    likes BIGINT,
    comments BIGINT,
    shares BIGINT,
    saves BIGINT,
    engagement_total_30d BIGINT,
    engagement_rate NUMERIC(10,5),
    avg_engagement_rate_by_followers NUMERIC(10,5),
    avg_engagement_per_day NUMERIC(12,4),
    avg_eng_rate_by_views NUMERIC(10,5),
    avg_eng_rate_by_impressions NUMERIC(10,5),
    avg_eng_rate_by_reach NUMERIC(10,5),
    avg_views BIGINT,
    reach_total_30d BIGINT,
    impressions_total_30d BIGINT,
    reels_views_30d BIGINT,
    top_post_views BIGINT,
    day_with_most_posts TEXT DEFAULT '',
    hour_with_most_posts TEXT DEFAULT '',
    day_with_highest_engagement TEXT DEFAULT '',
    hour_with_highest_engagement TEXT DEFAULT '',
    avg_hashtags_per_post NUMERIC(10,4),
    avg_video_duration_seconds NUMERIC(10,3),
    estimated_organic_value_cents BIGINT DEFAULT 0,
    vkpi_attributed_gmv_cents BIGINT DEFAULT 0,
    vkpi_attributed_orders BIGINT DEFAULT 0,
    vkpi_linked_kol_count BIGINT DEFAULT 0,
    vkpi_project_count BIGINT DEFAULT 0,
    youtube_kpi_status TEXT NOT NULL DEFAULT 'reserved',
    youtube_kpi_source_ref TEXT DEFAULT '',
    youtube_kpi_updated_at TIMESTAMPTZ,
    youtube_kpi_json TEXT NOT NULL DEFAULT '{}',
    raw_platform_data TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(account_id, snapshot_date)
);
