"""Single, plan-bound public YouTube discovery probe; no inventory writes.

The caller owns approval and local DB selection. This module never provisions a
budget. Missing configured budgets/fences fail closed at the canonical boundary.
Official run API usageTotalUsd is an observed total that may arrive late; a
positive observation is not final billing. usageUsd is NOT a fallback total.
https://docs.apify.com/api/client/js/reference/interface/ActorRun
"""
from __future__ import annotations

import json
import math
import os
import re
import time
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlsplit

from apify_client import ApifyClient

from app.domains.costs.budget_guard import record_apify_run
from app.domains.costs.apify_cost_reconciliation import observed_charge
from app.platform.apify_budget import (
    acquire_provider_execution_claim, apify_execution_context, call_apify_actor,
    finalize_provider_execution_claim,
)
from app.platform.apify_budget_contracts import (
    ApifyBudgetBlocked, ApifyExecutionClaimBlocked, ApifyProviderReplayBlocked,
)
from app.platform.apify_lifecycle import managed_apify_client as apify_client_scope


ACTOR_ID = "streamers~youtube-scraper"
BUILD = "0.0.290"
MAX_CHARGE_USD = 0.10
MAX_ITEMS = 10
TERMINAL = {"SUCCEEDED", "FAILED", "TIMED-OUT", "ABORTED"}
PUBLIC_FIELDS = (
    "id", "url", "title", "channelId", "channelName", "channelUrl",
    "channelUsername", "date", "viewCount", "likes", "commentsCount",
    "numberOfSubscribers", "duration", "videoLanguage", "defaultAudioLanguage",
)
_ID = re.compile(r"^[A-Za-z0-9_-]{1,128}$")
_PLAN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$")
_CONTACT = re.compile(r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|(?:\+?\d[\s().-]*){8,}")


def _finite(value: Any) -> bool:
    return type(value) in (int, float) and math.isfinite(value) and value >= 0


def _input(queries: Any) -> dict[str, Any]:
    if not isinstance(queries, list) or not 1 <= len(queries) <= 2:
        raise ValueError("queries_out_of_bounds")
    for query in queries:
        if (not isinstance(query, str) or not 1 <= len(query) <= 120
                or not re.fullmatch(r"[ -~]+", query) or not re.search(r"[A-Za-z]", query)):
            raise ValueError("query_out_of_bounds")
    return {
        "searchQueries": queries, "maxResults": 5, "maxResultsShorts": 0,
        "maxResultStreams": 0, "sortingOrder": "relevance", "videoType": "video",
        "downloadSubtitles": False, "saveSubsToKVS": False,
        "preferAutoGeneratedSubtitles": False,
        "aiVideoDescription": False, "aiVideoSummary": False,
    }


def _event(handle: Any, event: str, **fields: Any) -> None:
    handle.write(json.dumps({"event": event, **fields}, allow_nan=False) + "\n")
    handle.flush()
    os.fsync(handle.fileno())


def _client(token: str) -> Any:
    client = ApifyClient(token, api_url="https://api.apify.com", max_retries=0, timeout_secs=15)
    for name in ("httpx_client", "httpx_async_client"):
        transport = getattr(client.http_client, name, None)
        if transport is not None:
            transport.follow_redirects = False
    return client


class _BoundedClient:
    """Narrow SDK transport adapter: API supports restartOnError; SDK start doesn't.

    POST is invoked ONLY by call_apify_actor, after its real reservation/fence.
    SDK retries are zero. Auth stays in SDK headers, never URL/query parameters.
    """

    def __init__(self, client: Any, journal: Any):
        self.client, self.journal = client, journal
        self.deadline = time.monotonic() + 180
        self.run_id: str | None = None
        self.latest: dict[str, Any] = {}
        self.start_attempts = 0
        self.abort_status = "not_needed"

    def request(self, method: str, path: str, **kwargs: Any) -> Any:
        remaining = self.deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError("probe_deadline")
        return self.client.http_client.call(
            method=method, url="https://api.apify.com/v2/" + path,
            timeout_secs=min(15, remaining), **kwargs,
        )

    def remember(self, raw: Any) -> dict[str, Any]:
        if not isinstance(raw, dict) or not _ID.fullmatch(str(raw.get("id") or "")):
            raise ValueError("provider_run_id_missing")
        if self.run_id and self.run_id != raw["id"]:
            raise ValueError("provider_run_id_changed")
        first = self.run_id is None
        self.run_id, self.latest = raw["id"], raw
        if first:
            _event(self.journal, "provider_run_identified", run_id=self.run_id)
        return raw

    def actor(self, actor_id: str) -> "_BoundedClient":
        if actor_id != ACTOR_ID:
            raise ValueError("actor_not_allowed")
        return self

    def start(self, *, run_input: dict[str, Any], **options: Any) -> dict[str, Any]:
        if self.start_attempts:
            raise RuntimeError("provider_start_already_attempted")
        expected = {"build": BUILD, "timeout_secs": 120, "memory_mbytes": 1024,
                    "max_total_charge_usd": MAX_CHARGE_USD}
        if options != expected:
            raise ValueError("run_options_changed")
        # Fsync BEFORE the uncertain POST; known identity is fsynced immediately after.
        _event(self.journal, "provider_start_attempt", actor_id=ACTOR_ID, build=BUILD)
        self.start_attempts += 1
        response = self.request("POST", f"acts/{ACTOR_ID}/runs", json=run_input, params={
            "build": BUILD, "timeout": 120, "memory": 1024,
            "maxTotalChargeUsd": MAX_CHARGE_USD, "waitForFinish": 0, "restartOnError": False,
        })
        return self.remember(response.json().get("data"))

    def run(self, run_id: str) -> "_BoundedClient":
        if not _ID.fullmatch(run_id) or (self.run_id and self.run_id != run_id):
            raise ValueError("provider_run_id_changed")
        if self.run_id is None:
            self.run_id = run_id
            _event(self.journal, "provider_run_resumed", run_id=run_id)
        return self

    def get(self) -> dict[str, Any]:
        return self.wait_for_finish(wait_secs=0)

    def wait_for_finish(self, *, wait_secs: int) -> dict[str, Any]:
        response = self.request("GET", f"actor-runs/{self.run_id}", params={
            "waitForFinish": min(5, max(0, wait_secs)),
        })
        return self.remember(response.json().get("data"))

    def abort_if_active(self) -> None:
        if (not self.run_id or self.latest.get("status") in TERMINAL
                or self.abort_status != "not_needed"):
            return
        # Cleanup may use one independent 15s window for this KNOWN run only.
        # No actor start/restart is available on this path, even after main expiry.
        self.deadline = max(self.deadline, time.monotonic() + 15)
        self.abort_status = "attempted_unconfirmed"
        response = self.request("POST", f"actor-runs/{self.run_id}/abort",
                                params={"gracefully": False})
        self.remember(response.json().get("data"))
        if self.latest.get("status") not in TERMINAL:
            self.get()
        if self.latest.get("status") in TERMINAL:
            self.abort_status = "terminal_confirmed"
        _event(self.journal, "abort_result", run_id=self.run_id, status=self.abort_status)


def _public_item(raw: Any) -> dict[str, Any]:
    if not isinstance(raw, dict):
        return {}
    item: dict[str, Any] = {}
    for key in PUBLIC_FIELDS:
        value = raw.get(key)
        if isinstance(value, str):
            if key == "date":
                try:
                    datetime.fromisoformat(value.replace("Z", "+00:00"))
                except ValueError:
                    continue
                item[key] = value  # Preserve actual precision/timezone; not a phone number.
                continue
            if key in {"url", "channelUrl"}:
                try:
                    parts = urlsplit(value)
                    valid = (parts.scheme == "https" and parts.hostname in {
                        "www.youtube.com", "youtube.com", "m.youtube.com", "youtu.be",
                    } and not parts.username and not parts.password and not parts.fragment
                        and not parts.port and not re.search(r"\s", value)
                        and all(name == "v" and _ID.fullmatch(val)
                                for name, val in parse_qsl(parts.query, keep_blank_values=True)))
                except ValueError:
                    valid = False
                if not valid or len(value) > 500:
                    continue
            if key in {"id", "channelId", "channelUsername"}:
                if not re.fullmatch(r"[@A-Za-z0-9_-]{1,128}", value):
                    continue
            item[key] = (_CONTACT.sub("[redacted]", value[:500])
                         if key not in {"id", "channelId", "url", "channelUrl", "channelUsername"}
                         else value)
        elif _finite(value):
            item[key] = value
    return item


def _read_items(client: _BoundedClient, run: dict[str, Any]) -> tuple[list, bool]:
    dataset_id = str(run.get("defaultDatasetId") or "")
    if not _ID.fullmatch(dataset_id):
        raise ValueError("dataset_id_missing")
    response = client.request("GET", f"datasets/{dataset_id}/items", params={
        "format": "json", "limit": MAX_ITEMS, "offset": 0, "clean": True,
        "fields": ",".join(PUBLIC_FIELDS),
    })
    raw = response.json()
    if not isinstance(raw, list):
        raise ValueError("dataset_invalid")
    items = [_public_item(item) for item in raw[:MAX_ITEMS]]
    total = str(response.headers.get("x-apify-pagination-total", ""))
    complete = total.isdigit() and int(total) == len(raw) and len(raw) <= MAX_ITEMS
    return items, complete


def _cost_evidence(run: dict[str, Any]) -> dict[str, Any]:
    evidence = {key: run[key] for key in ("usageTotalUsd",)
                if _finite(run.get(key))}
    for key in ("usageUsd", "chargedEventCounts"):
        values = run.get(key)
        if isinstance(values, dict):
            evidence[key] = {name: val for name, val in values.items()
                             if _ID.fullmatch(str(name)) and _finite(val)}
    pricing = run.get("pricingInfo")
    if isinstance(pricing, dict):
        evidence["pricingInfo"] = {"pricingModel": pricing.get("pricingModel")}
        per_event = pricing.get("pricingPerEvent")
        events = per_event.get("actorChargeEvents", {}) if isinstance(per_event, dict) else {}
        prices = {}
        if isinstance(events, dict):
            for name, row in events.items():
                if not _ID.fullmatch(str(name)) or not isinstance(row, dict):
                    continue
                prices[name] = {key: row[key] for key in ("eventPriceUsd",)
                                if _finite(row.get(key))}
                tiers = row.get("eventTieredPricingUsd")
                if isinstance(tiers, dict):
                    prices[name]["eventTieredPricingUsd"] = {
                        tier: {"tieredEventPriceUsd": value["tieredEventPriceUsd"]}
                        for tier, value in tiers.items() if _ID.fullmatch(str(tier))
                        and isinstance(value, dict) and _finite(value.get("tieredEventPriceUsd"))
                    }
        evidence["pricingInfo"]["pricingPerEvent"] = {"actorChargeEvents": prices}
    return evidence


def _account(run: dict[str, Any], result: dict[str, Any]) -> None:
    result["cost_evidence"] = _cost_evidence(run)
    amount = observed_charge(run)
    if amount is None:
        return  # Zero may be legitimate, or still pending. Do not estimate/settle zero.
    # A positive early run usage is an observation, not a final bill. The
    # canonical ledger records it and later reconciles only the same run ID.
    result.update(cost_status="provisional", cost_state="provisional",
                  cost_usd=float(amount), provider_cost_final=False)
    key = str(run.get("_vkpi_budget_reservation_key") or "")
    if not key:
        result["accounting_status"] = "reservation_identity_missing"
        return
    recorded = record_apify_run(run, actor_id=ACTOR_ID, platform="youtube",
                                operation="kol_live_query_eval", source="manual_live_probe",
                                dataset_item_count=result["item_count"])
    result["accounting_status"] = (
        "recorded" if recorded.get("recorded") is True else "ledger_unconfirmed"
    )


def _execute(client: _BoundedClient, payload: dict, result: dict) -> None:
    run = call_apify_actor(
        client, ACTOR_ID, platform="youtube", operation="kol_live_query_eval",
        source="manual_live_probe", estimated_cost_usd=MAX_CHARGE_USD,
        run_input=payload, build=BUILD, timeout_secs=120, memory_mbytes=1024,
        max_total_charge_usd=MAX_CHARGE_USD, wait_secs=120,
    )
    if run.get("status") not in TERMINAL:
        client.abort_if_active()
        run = {**run, **client.latest}
    result["provider_status"] = run.get("status", "UNKNOWN")
    result["execution_state"] = ("succeeded" if run.get("status") == "SUCCEEDED"
        else "failed" if run.get("status") in TERMINAL else "unknown")
    if run.get("status") == "SUCCEEDED":
        try:
            result["items"], result["read_complete"] = _read_items(client, run)
        except Exception as exc:
            result["read_error_type"] = type(exc).__name__
            result["read_complete"] = False
        result["item_count"] = len(result["items"])
        result["data_state"] = "complete" if result["read_complete"] else "partial"
    _account(run, result)
    if run.get("status") != "SUCCEEDED":
        result.update(status="failed", reason="provider_not_succeeded")
    elif not result["read_complete"]:
        result.update(status="partial", reason="dataset_read_incomplete")
    elif result["accounting_status"] != "recorded":
        result.update(status="partial", reason="cost_or_accounting_unconfirmed")
    else:
        result.update(status="partial", reason="cost_finality_unconfirmed")


def run_probe(queries: list[str], output_dir: str | Path, plan_id: str) -> dict[str, Any]:
    """Explicit live entry. Importing this module performs no provider/DB calls."""
    payload = _input(queries)
    if not isinstance(plan_id, str) or not _PLAN.fullmatch(plan_id):
        raise ValueError("plan_id_invalid")
    target = Path(output_dir).resolve()
    target.mkdir(parents=True, exist_ok=True)
    events_path, result_path = target / "apify-events.jsonl", target / "apify-result.json"
    # Exclusive journal prevents accidental second execution in the same plan dir.
    fd = os.open(events_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    result: dict[str, Any] = {
        "status": "blocked", "reason": "not_started", "plan_id": plan_id,
        "queries": queries, "actor_id": ACTOR_ID, "build": BUILD, "run_id": None,
        "provider_status": "NOT_STARTED", "items": [], "item_count": 0,
        "read_complete": False, "cost_status": "unknown", "cost_usd": None,
        "execution_state": "not_started", "data_state": "not_read", "cost_state": "unknown",
        "provider_cost_final": False, "automatic_provider_retry_allowed": False,
        "accounting_status": "not_settled", "claim_status": "descriptive_only",
        "events_path": str(events_path), "result_path": str(result_path),
        "provider_start_attempts": 0, "cleanup_status": "not_created",
        "execution_claim_status": "not_acquired",
    }
    task_id, fence, bounded, sdk = f"kol-live:{plan_id}", None, None, None
    with os.fdopen(fd, "w", encoding="utf-8") as journal:
        try:
            token = next((os.environ[key].strip() for key in
                          ("APIFY_TOKEN", "APIFY_API_TOKEN", "APIFY_API_KEY")
                          if os.environ.get(key, "").strip()), "")
            if not token:
                result["reason"] = "apify_not_configured"
                return _finish(result, journal, result_path)
            fence = acquire_provider_execution_claim(task_id, f"manual:{plan_id}",
                                                     job_type="kol_live_probe", lease_seconds=240)
            result["execution_claim_status"] = "active"
            sdk = _client(token)
            with apify_client_scope(sdk), apify_execution_context(task_id, fence):
                bounded = _BoundedClient(sdk, journal)
                try:
                    _execute(bounded, payload, result)
                finally:
                    try:
                        bounded.abort_if_active()
                    except Exception:
                        bounded.abort_status = "attempted_unconfirmed"
        except (ApifyBudgetBlocked, ApifyExecutionClaimBlocked, ApifyProviderReplayBlocked):
            result.update(status="blocked", reason="canonical_provider_guard_blocked")
        except Exception as exc:
            result.update(status="unknown", reason="probe_failed", error_type=type(exc).__name__)
            status = getattr(exc, "status_code", None)
            if type(status) is int and 100 <= status <= 599:
                result["http_status"] = status
        finally:
            if bounded is not None:
                result.update(run_id=bounded.run_id, provider_start_attempts=bounded.start_attempts,
                              abort_status=bounded.abort_status)
                result["provider_status"] = bounded.latest.get("status", result["provider_status"])
                result["execution_state"] = ("succeeded" if result["provider_status"] == "SUCCEEDED"
                    else "failed" if result["provider_status"] in TERMINAL else "unknown")
                if bounded.run_id:
                    result["next_action"] = ("reconcile_existing_run_cost" if result["data_state"] == "complete"
                        else "read_existing_run_or_dataset")
            if sdk is not None:
                result["cleanup_status"] = (
                    "closed" if getattr(sdk, "_vkpi_apify_lifecycle_closed", False) else "unconfirmed"
                )
            if fence is not None:
                # Data/cost incompleteness is not an execution retry signal.
                state = ("completed" if result["execution_state"] == "succeeded" else
                         "failed" if result["execution_state"] == "failed" else
                         "blocked" if result["status"] == "blocked" else "unknown")
                try:
                    finalized = finalize_provider_execution_claim(task_id, fence, state)
                    result["execution_claim_status"] = state if finalized else "finalization_unconfirmed"
                except Exception:
                    result["execution_claim_status"] = "finalization_unconfirmed"
                if result["execution_claim_status"] == "finalization_unconfirmed":
                    result.update(status="partial", reason="claim_finalization_unconfirmed")
            if result["status"] == "completed" and result["cleanup_status"] != "closed":
                result.update(status="partial", reason="client_cleanup_unconfirmed")
        return _finish(result, journal, result_path)


def _finish(result: dict, journal: Any, path: Path) -> dict:
    _event(journal, "probe_result", status=result["status"], run_id=result["run_id"],
           cost_status=result["cost_status"], accounting_status=result["accounting_status"])
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        json.dump(result, handle, ensure_ascii=False, indent=2, allow_nan=False)
        handle.flush()
        os.fsync(handle.fileno())
    return result
