export * from "./vkpi";
export * from "./vkpi/alert-api";
export * from "./vkpi/attribution-api";
export * from "./vkpi/audit-api";
export * from "./vkpi/channel-api";
export * from "./vkpi/comment-intelligence-api";
export * from "./vkpi/cost-api";
export * from "./vkpi/data-quality-api";
export * from "./vkpi/evidence-api";
export * from "./vkpi/feedback-api";
export * from "./vkpi/firewall-api";
export * from "./vkpi/industry-api";
export * from "./vkpi/intelligence-api";
export * from "./vkpi/kol-api";
export * from "./vkpi/kolPool-api";
export * from "./vkpi/links-api";
export * from "./vkpi/market-api";
export * from "./vkpi/media-api";
export * from "./vkpi/product-api";
export * from "./vkpi/projects-api";
export * from "./vkpi/repair-api";
export * from "./vkpi/search-api";
export * from "./vkpi/settings-api";
export * from "./vkpi/staff-api";
export * from "./vkpi/sync-api";
export * from "./vkpi/tasks-api";

type LegacyRepairItem = {
  [key: string]: any;
  acceptance?: string[];
  evidence?: string[];
  fields?: LegacyRepairItem[];
  requiredBeforeWrite?: string[];
  required_before_write?: string[];
  validationCommands?: string[];
  validation_commands?: string[];
};
type LegacyRepairPayload = {
  [key: string]: any;
  proposals?: LegacyRepairItem[];
  rows?: LegacyRepairItem[];
  gates?: LegacyRepairItem[];
  tables?: LegacyRepairItem[];
  endpoints?: LegacyRepairItem[];
  blockedBy?: string[];
  blocked_by?: string[];
  artifacts?: LegacyRepairItem[];
  steps?: LegacyRepairItem[];
  upSql?: LegacyRepairItem[];
  up_sql?: LegacyRepairItem[];
  downSql?: LegacyRepairItem[];
  down_sql?: LegacyRepairItem[];
  reviewCommands?: string[];
  review_commands?: string[];
  events?: LegacyRepairItem[];
  drafts?: LegacyRepairItem[];
  refs?: LegacyRepairItem[];
  fields?: LegacyRepairItem[];
  requiredBeforePersist?: string[];
  required_before_persist?: string[];
  persistencePreview?: LegacyRepairPayload;
  persistence_preview?: LegacyRepairPayload;
};
export type VkpiRepairPersistencePreview = LegacyRepairPayload;
export type VkpiRepairProposalRecord = LegacyRepairPayload;
