"""
Core index setup for app.db.migrations.
"""
from __future__ import annotations

from typing import Any


CORE_INDEX_STATEMENTS = (
    "CREATE INDEX IF NOT EXISTS idx_submissions_user_created ON submissions(user_id, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON submissions(created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_detection_created ON submissions(detection_status, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_job_status ON submissions(job_status, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_platform_created ON submissions(platform, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_series_created ON submissions(product_series, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_handle_created ON submissions(extracted_handle, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_submissions_points_status ON submissions(points_status, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_social_user_platform ON user_social_accounts(user_id, platform, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_social_handle_verified ON user_social_accounts(handle, verified)",
    "CREATE INDEX IF NOT EXISTS idx_user_addresses_user_default ON user_addresses(user_id, is_default, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_redemptions_user_created ON redemptions(user_id, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_redemptions_status_created ON redemptions(status, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_points_log_user_created ON points_log(user_id, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role, status, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_email_tokens_user_type ON email_tokens(user_id, type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_verifications_user_created ON verifications(user_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_verifications_status_created ON verifications(status, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_verifications_platform_status ON verifications(platform, status, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_reward_catalog_status_sort ON reward_catalog(status, sort_order, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_assets_submission ON submission_assets(submission_id)",
    "CREATE INDEX IF NOT EXISTS idx_assets_role ON submission_assets(asset_role)",
    "CREATE INDEX IF NOT EXISTS idx_assets_checksum ON submission_assets(checksum)",
    "CREATE INDEX IF NOT EXISTS idx_assets_pending_cleanup ON submission_assets(submission_id, asset_role, deleted_at, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_asset_fp_asset_type ON asset_fingerprints(asset_id, fingerprint_type)",
    "CREATE INDEX IF NOT EXISTS idx_asset_fp_value_type ON asset_fingerprints(fingerprint_value, fingerprint_type)",
    "CREATE INDEX IF NOT EXISTS idx_pcache_expires ON persistent_cache(expires_at)",
    "CREATE INDEX IF NOT EXISTS idx_rlog_blocked ON rate_limit_log(blocked_at)",
    "CREATE INDEX IF NOT EXISTS idx_bh_snapshot ON bh_products(snapshot_at)",
    "CREATE INDEX IF NOT EXISTS idx_bh_sku ON bh_products(sku)",
    "CREATE INDEX IF NOT EXISTS idx_bh_title ON bh_products(title)",
    "CREATE INDEX IF NOT EXISTS idx_bh_rating ON bh_products(rating DESC, review_count DESC)",
    "CREATE INDEX IF NOT EXISTS idx_ingest_platform_status ON platform_ingest_events(source_platform, ingest_status, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_ingest_entity_external ON platform_ingest_events(entity_type, external_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_ingest_region_created ON platform_ingest_events(region_code, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_creator_memory_handle_kind ON creator_memory_entries(creator_handle, memory_kind, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_creator_memory_user_kind ON creator_memory_entries(user_id, memory_kind, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_market_obs_platform_subject ON market_observations(source_platform, subject_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_market_obs_region_created ON market_observations(region_code, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_vx_accounts_platform_active ON viltrox_matrix_accounts(platform, is_active, name)",
    "CREATE INDEX IF NOT EXISTS idx_vx_runs_completed ON viltrox_matrix_scan_runs(completed_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_vx_scan_accounts_run_account ON viltrox_matrix_scan_accounts(run_id, account_id)",
    "CREATE INDEX IF NOT EXISTS idx_vx_scan_posts_run_published ON viltrox_matrix_scan_posts(run_id, published_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_vx_scan_posts_account_published ON viltrox_matrix_scan_posts(account_id, published_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_product_visual_product_type ON product_visual_features(product_key, feature_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_region_facts_region_type ON region_market_facts(region_code, fact_type, observed_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_feedback_source_event ON feedback_events(source_type, event_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_feedback_submission_created ON feedback_events(submission_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_trust_events_user_created ON trust_events(user_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_trust_events_event_created ON trust_events(event_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_personas_user_updated ON via_personas(user_id, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_sessions_user_updated ON via_sessions(user_id, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_sessions_persona_updated ON via_sessions(persona_id, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_sessions_device_updated ON via_sessions(signed_device_id, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_memory_session_created ON via_memory_refs(session_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_memory_kind_created ON via_memory_refs(memory_kind, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_decision_session_created ON via_decision_ledger(session_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_decision_type_created ON via_decision_ledger(decision_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_outcome_session_created ON via_outcome_ledger(session_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_outcome_decision_created ON via_outcome_ledger(decision_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_reward_trace_session_created ON via_reward_traces(session_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_reward_trace_decision_created ON via_reward_traces(decision_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_reward_trace_event_created ON via_reward_traces(event_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_reward_trace_idempotency ON via_reward_traces(session_key, idempotency_key)",
    "CREATE INDEX IF NOT EXISTS idx_via_retrieval_evidence_session_created ON via_retrieval_evidence(session_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_retrieval_evidence_decision_created ON via_retrieval_evidence(decision_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_proposal_policy_updated ON via_policy_proposals(policy_key, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_proposal_status_updated ON via_policy_proposals(status, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_policy_versions_policy_created ON via_policy_versions(policy_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_policy_versions_status_policy ON via_policy_versions(status, policy_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_rollout_alerts_policy_created ON via_rollout_alerts(policy_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_rollout_alerts_version_created ON via_rollout_alerts(version_key, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_routing_stats_bucket_provider ON via_routing_provider_stats(bucket_key, provider, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_memory_retention_source_updated ON via_memory_retention_stats(source_ref, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_via_memory_retention_user_updated ON via_memory_retention_stats(user_id, updated_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_schools_code_name ON schools(school_code, school_name)",
    "CREATE INDEX IF NOT EXISTS idx_student_qr_school_status ON student_qr_codes(school_id, status, issued_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_qr_batch_serial ON student_qr_codes(issued_batch, display_serial)",
    "CREATE INDEX IF NOT EXISTS idx_student_qr_user_bound ON student_qr_codes(bound_user_id, bound_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_verifications_user_status ON student_verifications(user_id, status, verified_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_verifications_school_status ON student_verifications(school_id, status, verified_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_scan_events_user_created ON student_scan_events(user_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_scan_events_qr_created ON student_scan_events(qr_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_audit_qr_created ON student_identity_audit_log(qr_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_student_audit_user_created ON student_identity_audit_log(user_id, created_at DESC)",
)


def create_core_indexes(c: Any) -> None:
    for statement in CORE_INDEX_STATEMENTS:
        c.execute(statement)
