import {
  claimOutreachSuggestion,
  createProductLaunch,
  createProjectFromOutreachSuggestion,
  dismissOutreachSuggestion,
  generateDailyOutreachDigest,
  getDailyOutreachDigestStatus,
  getProductRecommendationEvidence,
  getProductRecommendationOutcomeSummary,
  importProductKolPool,
  listAnalyticsProducts,
  listDailyOutreachDigest,
  listOutreachSuggestions,
  listProductLaunches,
  listProductRecommendationRuns,
  listProductRecommendations,
  productRecommendationAction,
  runProductCompare,
  runProductMonitor,
  runProductRecommendations,
  upsertAnalyticsProduct,
} from '../../services/vkpi/product-api';
import { getKolPoolSummary } from '../../services/vkpi/kolPool-api';

export type ProductDomainRow = Record<string, unknown>;

export {
  claimOutreachSuggestion,
  createProductLaunch,
  createProjectFromOutreachSuggestion,
  dismissOutreachSuggestion,
  generateDailyOutreachDigest,
  getDailyOutreachDigestStatus,
  getKolPoolSummary,
  getProductRecommendationEvidence,
  getProductRecommendationOutcomeSummary,
  importProductKolPool,
  listAnalyticsProducts,
  listDailyOutreachDigest,
  listOutreachSuggestions,
  listProductLaunches,
  listProductRecommendationRuns,
  listProductRecommendations,
  productRecommendationAction,
  runProductCompare,
  runProductMonitor,
  runProductRecommendations,
  upsertAnalyticsProduct,
};
