"""
services/via/vector_memory.py — Optional vector memory layer for Via
"""
from __future__ import annotations

import asyncio
import hashlib
import json
import sys
import uuid
from typing import Any

import httpx

from app.core.config import (
    QDRANT_API_KEY,
    QDRANT_COLLECTION,
    QDRANT_LOCAL_PATH,
    QDRANT_URL,
    VIA_BGE_MODEL,
    VIA_EMBEDDING_BACKEND,
    VIA_EMBEDDING_MODEL,
    VIA_VECTOR_BACKEND,
    VIA_VECTOR_TOP_K,
    WEAVIATE_API_KEY,
    WEAVIATE_CLASS,
    WEAVIATE_URL,
)
from app.core.logging import get_logger
from app.services.ai.clients.openai_client import OPENAI_AVAILABLE, openai_client
from app.services.via.model_router import summarize_via_exchange
from app.services.via.vector_memory_backends import (
    NullVectorBackend as _NullVectorBackendImpl,
    QdrantVectorBackend as _QdrantVectorBackendImpl,
    WeaviateVectorBackend as _WeaviateVectorBackendImpl,
)
from app.services.via.vector_memory_embeddings import (
    embed_bge_sync as _embed_bge_sync_impl,
    embed_openai_sync as _embed_openai_sync_impl,
    embed_texts as _embed_texts_impl,
)

try:
    from qdrant_client import QdrantClient
    from qdrant_client.http import models as qdrant_models
except Exception:  # pragma: no cover - optional local backend
    QdrantClient = None
    qdrant_models = None

try:
    from sentence_transformers import SentenceTransformer
except Exception:  # pragma: no cover - optional local backend
    SentenceTransformer = None

_bge_encoder: Any | None = None
_vector_backend_singleton: Any | None = None
logger = get_logger(__name__)

# 护栏③ enforce:per-request embedding 批量硬上限。当前最大真实批次=128(seed 路径
# knowledge_seed.build_via_seed_documents -> docs[:128]),128 不截断现有调用又挡住失控 fan-out。
MAX_EMBED_BATCH = 128


def _response_json_object(response: httpx.Response, operation: str) -> dict[str, Any]:
    response.raise_for_status()
    try:
        data = response.json()
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{operation}: invalid JSON response") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{operation}: expected JSON object response")
    return data


def _operation_error(operation: str, exc: Exception) -> str:
    if isinstance(exc, httpx.HTTPStatusError):
        status_code = exc.response.status_code
        return f"{operation}: HTTP {status_code}"
    name = type(exc).__name__.lower()
    message = str(exc).lower()
    if "timeout" in name or "timeout" in message or "deadline" in message:
        return "embedding timeout" if operation == "embedding" else f"{operation}: timeout"
    if operation.startswith("qdrant_local") and "lock" in message:
        return f"{operation}: local store locked"
    # These ValueErrors are generated by the response validators above and contain
    # protocol state only. External exception text is never copied into responses.
    if isinstance(exc, ValueError) and str(exc).startswith(f"{operation}: "):
        return str(exc)[:300]
    return f"{operation}: unavailable"


def _qdrant_result(response: httpx.Response, operation: str) -> Any:
    data = _response_json_object(response, operation)
    if data.get("status") != "ok":
        raise ValueError(f"{operation}: Qdrant status is not ok")
    if "result" not in data:
        raise ValueError(f"{operation}: Qdrant response missing result")
    return data["result"]


def _validate_qdrant_collection(result: Any, operation: str, expected_dim: int | None = None) -> None:
    if not isinstance(result, dict):
        raise ValueError(f"{operation}: invalid Qdrant collection result")
    collection_status = str(result.get("status") or "").strip().lower()
    if collection_status not in {"green", "yellow", "grey"}:
        raise ValueError(f"{operation}: Qdrant collection status is {collection_status or 'missing'}")
    if expected_dim is None:
        return
    vector_config = (((result.get("config") or {}).get("params") or {}).get("vectors") or {})
    if not isinstance(vector_config, dict) or "size" not in vector_config:
        raise ValueError(f"{operation}: Qdrant collection vector size missing")
    try:
        actual_dim = int(vector_config["size"])
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{operation}: invalid Qdrant collection vector size") from exc
    if actual_dim != expected_dim:
        raise ValueError(f"{operation}: Qdrant vector size {actual_dim} does not match {expected_dim}")


def _validate_weaviate_class(data: dict[str, Any], operation: str) -> None:
    class_name = str(data.get("class") or "").strip()
    if class_name != WEAVIATE_CLASS:
        raise ValueError(f"{operation}: Weaviate class mismatch")


def _stable_id(*parts: Any) -> str:
    raw = "|".join(str(part or "").strip() for part in parts if str(part or "").strip())
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return str(uuid.UUID(digest[:32]))


def via_namespace_for_bundle(bundle: dict[str, Any]) -> str:
    persona = bundle.get("persona") or {}
    session = bundle.get("session") or {}
    persona_key = str(persona.get("persona_key") or "").strip()
    if persona_key:
        return persona_key
    user_id = int(session.get("user_id") or persona.get("user_id") or 0)
    if user_id:
        return f"user:{user_id}:primary"
    session_key = str(session.get("session_key") or "").strip()
    return f"anon:{session_key or 'default'}"


def _ref_text(item: dict[str, Any]) -> str:
    payload = item.get("payload") or {}
    summary = str(payload.get("summary") or "").strip()
    if summary:
        return summary
    fact_value = payload.get("fact_value_json")
    if isinstance(fact_value, str) and fact_value.strip():
        return fact_value[:500]
    if isinstance(fact_value, (dict, list)):
        return json.dumps(fact_value, ensure_ascii=False)[:500]
    parts = [
        str(item.get("memory_kind") or "").strip(),
        str(item.get("memory_key") or "").strip(),
        str(item.get("source_ref") or "").strip(),
    ]
    return " | ".join(part for part in parts if part)[:300]


def _ref_payload(namespace: str, session_key: str, user_id: int, item: dict[str, Any], summary: str) -> dict[str, Any]:
    payload = item.get("payload") or {}
    return {
        "namespace": namespace,
        "session_key": session_key,
        "user_id": int(user_id or 0),
        "memory_kind": str(item.get("memory_kind") or "vector_memory"),
        "memory_key": str(item.get("memory_key") or ""),
        "source_ref": str(item.get("source_ref") or ""),
        "summary": summary[:300],
        "payload_json": json.dumps(payload, ensure_ascii=False)[:3000],
    }


def _conversation_text(user_text: str, reply_text: str, summary: str, keywords: list[str], traits: dict[str, Any], current_surface: str) -> str:
    parts = [
        f"summary: {summary}",
        f"user: {str(user_text or '').strip()}",
        f"reply: {str(reply_text or '').strip()}",
        f"keywords: {', '.join(keywords)}" if keywords else "",
        f"traits: {json.dumps(traits, ensure_ascii=False)}" if traits else "",
        f"surface: {current_surface}",
    ]
    return "\n".join(part for part in parts if part).strip()[:4000]


def _dedupe_refs(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: set[tuple[str, str]] = set()
    out: list[dict[str, Any]] = []
    for item in items:
        key = (str(item.get("memory_kind") or ""), str(item.get("source_ref") or item.get("memory_key") or ""))
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def _seed_payload(
    namespace: str,
    session_key: str,
    user_id: int,
    item: dict[str, Any],
) -> dict[str, Any]:
    payload = dict(item.get("payload") or {})
    payload.update(
        {
            "namespace": namespace,
            "session_key": session_key,
            "user_id": int(user_id or 0),
            "memory_kind": str(item.get("memory_kind") or "seed_doc"),
            "memory_key": str(item.get("memory_key") or ""),
            "source_ref": str(item.get("source_ref") or ""),
            "summary": str(item.get("summary") or item.get("text") or "")[:300],
            "text_snippet": str(item.get("text") or payload.get("text_snippet") or "")[:1200],
            "payload_json": json.dumps(item.get("payload") or {}, ensure_ascii=False)[:3000],
        }
    )
    return payload


def _embed_openai_sync(texts: list[str]) -> list[list[float]]:
    return _embed_openai_sync_impl(
        texts,
        openai_available=OPENAI_AVAILABLE,
        openai_client=openai_client,
        model=VIA_EMBEDDING_MODEL,
        max_batch=MAX_EMBED_BATCH,
    )


def _embed_bge_sync(texts: list[str]) -> list[list[float]]:
    global _bge_encoder
    vectors, _bge_encoder = _embed_bge_sync_impl(
        texts,
        encoder=_bge_encoder,
        sentence_transformer=SentenceTransformer,
        model=VIA_BGE_MODEL,
    )
    return vectors


async def _embed_texts(texts: list[str]) -> list[list[float]]:
    return await _embed_texts_impl(
        texts,
        backend=VIA_EMBEDDING_BACKEND,
        embed_bge=_embed_bge_sync,
        embed_openai=_embed_openai_sync,
        to_thread=asyncio.to_thread,
    )


class _NullVectorBackend(_NullVectorBackendImpl):
    pass


class _QdrantVectorBackend(_QdrantVectorBackendImpl):
    def __init__(self) -> None:
        super().__init__(sys.modules[__name__])


class _WeaviateVectorBackend(_WeaviateVectorBackendImpl):
    def __init__(self) -> None:
        super().__init__(sys.modules[__name__])


def _backend_operation_status(backend: Any) -> dict[str, Any]:
    get_status = getattr(backend, "operation_status", None)
    if not callable(get_status):
        return {"ready": False, "error": "vector backend status unavailable"}
    try:
        status = get_status()
    except Exception as exc:  # noqa: BLE001
        return {"ready": False, "error": _operation_error("vector_backend_status", exc)}
    if not isinstance(status, dict):
        return {"ready": False, "error": "vector backend returned invalid status"}
    return {
        "ready": bool(status.get("ready")),
        "error": str(status.get("error") or ""),
    }


def _vector_write_status(backend: Any, *, requested: int, upserted: int) -> dict[str, Any]:
    backend_status = _backend_operation_status(backend)
    if requested <= 0:
        return {**backend_status, "status": "skipped", "reason": "no_documents"}
    if upserted == requested and backend_status["ready"]:
        return {**backend_status, "status": "ready", "reason": ""}
    reason = backend_status["error"] or (
        "partial_upsert" if 0 < upserted < requested else "vector_backend_unavailable"
    )
    return {**backend_status, "status": "partial", "reason": str(reason)[:300]}


def build_via_vector_backend() -> Any:
    global _vector_backend_singleton
    if _vector_backend_singleton is not None:
        return _vector_backend_singleton
    if VIA_VECTOR_BACKEND == "qdrant":
        _vector_backend_singleton = _QdrantVectorBackend()
    elif VIA_VECTOR_BACKEND == "weaviate":
        _vector_backend_singleton = _WeaviateVectorBackend()
    else:
        _vector_backend_singleton = _NullVectorBackend()
    return _vector_backend_singleton


async def sync_bundle_memory_refs_to_vector(bundle: dict[str, Any]) -> dict[str, Any]:
    backend = build_via_vector_backend()
    namespace = via_namespace_for_bundle(bundle)
    session = bundle.get("session") or {}
    user_id = int(session.get("user_id") or 0)
    docs = []
    for item in _dedupe_refs(bundle.get("memory_refs") or [])[:24]:
        summary = _ref_text(item)
        if not summary:
            continue
        docs.append(
            {
                "id": _stable_id(namespace, item.get("memory_kind"), item.get("source_ref"), item.get("memory_key"), summary[:120]),
                "text": summary,
                "payload": _ref_payload(namespace, str(session.get("session_key") or ""), user_id, item, summary),
            }
        )
    try:
        count = await backend.upsert(namespace, docs)
    except Exception as exc:  # noqa: BLE001 - optional vector memory must not fail the request
        logger.warning("via.vector_memory.sync_failed", exc_info=True)
        count = 0
        status = {
            "ready": False,
            "error": _operation_error("vector_memory_sync", exc),
            "status": "partial",
            "reason": "vector_memory_sync_failed",
        }
    else:
        status = _vector_write_status(backend, requested=len(docs), upserted=count)
    return {
        "backend": getattr(backend, "backend_name", "none"),
        "namespace": namespace,
        "upserted": count,
        **status,
    }


async def recall_via_vector_memory(bundle: dict[str, Any], query_text: str, limit: int = VIA_VECTOR_TOP_K) -> list[dict[str, Any]]:
    backend = build_via_vector_backend()
    namespace = via_namespace_for_bundle(bundle)
    try:
        hits = await backend.search(namespace, query_text, max(1, int(limit)))
    except Exception:  # noqa: BLE001 - recall is optional; lexical/context paths remain available
        logger.warning("via.vector_memory.recall_failed", exc_info=True)
        return []
    if not isinstance(hits, list):
        logger.warning("via.vector_memory.invalid_recall_result")
        return []
    refs = []
    for hit in hits:
        if not isinstance(hit, dict):
            logger.warning("via.vector_memory.invalid_recall_hit")
            continue
        payload = hit.get("payload") or {}
        if not isinstance(payload, dict):
            logger.warning("via.vector_memory.invalid_recall_payload")
            continue
        summary = str(payload.get("summary") or "").strip()
        try:
            weight = float(hit.get("score") or 0.0)
        except (TypeError, ValueError):
            logger.warning("via.vector_memory.invalid_recall_score")
            continue
        refs.append({
            "memory_kind": "vector_recall",
            "source_ref": str(payload.get("source_ref") or hit.get("id") or ""),
            "memory_key": str(payload.get("memory_key") or ""),
            "weight": weight,
            "payload": {
                "summary": summary[:240],
                "text_snippet": str(payload.get("text_snippet") or "")[:600],
                "source": "vector_memory",
                "session_key": payload.get("session_key") or "",
                "payload_json": payload.get("payload_json") or "{}",
            },
        })
    return _dedupe_refs(refs)


async def store_via_vector_exchange(
    bundle: dict[str, Any],
    *,
    user_text: str,
    reply_text: str,
    signals: dict[str, Any] | None = None,
    current_surface: str = "upload",
) -> dict[str, Any]:
    backend = build_via_vector_backend()
    namespace = via_namespace_for_bundle(bundle)
    session = bundle.get("session") or {}
    persona = bundle.get("persona") or {}
    summary_error = ""
    try:
        summary_block = await summarize_via_exchange(
            user_text=user_text,
            reply_text=reply_text,
            signals=signals or {},
            current_surface=current_surface,
        )
        if not isinstance(summary_block, dict):
            raise ValueError("summary provider returned a non-object result")
    except Exception as exc:  # noqa: BLE001 - preserve the exchange with deterministic fallback text
        logger.warning("via.vector_memory.summary_failed", exc_info=True)
        summary_error = _operation_error("summary", exc)
        summary_block = {
            "summary": str((signals or {}).get("summary") or user_text or "").strip()[:180],
            "keywords": [
                str(item).strip()[:40]
                for item in list((signals or {}).get("keywords") or [])[:8]
                if str(item).strip()
            ],
            "provider": "fallback",
            "model": "",
        }
    text = _conversation_text(
        user_text,
        reply_text,
        summary_block.get("summary") or "",
        summary_block.get("keywords") or [],
        (signals or {}).get("traits") or {},
        current_surface,
    )
    source_ref = f"via-vector:{session.get('session_key')}:{_stable_id(user_text, reply_text)[:16]}"
    doc = {
        "id": _stable_id(namespace, source_ref),
        "text": text,
        "payload": {
            "namespace": namespace,
            "session_key": str(session.get("session_key") or ""),
            "user_id": int(session.get("user_id") or 0),
            "persona_key": str(persona.get("persona_key") or ""),
            "memory_kind": "conversation_signal",
            "memory_key": str(summary_block.get("summary") or "")[:120],
            "source_ref": source_ref,
            "summary": str(summary_block.get("summary") or "")[:300],
            "payload_json": json.dumps(
                {
                    "keywords": summary_block.get("keywords") or [],
                    "traits": (signals or {}).get("traits") or {},
                    "surface": current_surface,
                },
                ensure_ascii=False,
            )[:3000],
        },
    }
    try:
        upserted = await backend.upsert(namespace, [doc])
    except Exception as exc:  # noqa: BLE001
        logger.warning("via.vector_memory.exchange_upsert_failed", exc_info=True)
        upserted = 0
        vector_status = {
            "ready": False,
            "error": _operation_error("vector_exchange_upsert", exc),
            "status": "partial",
            "reason": "vector_exchange_upsert_failed",
        }
    else:
        vector_status = _vector_write_status(backend, requested=1, upserted=upserted)
    result = {
        "backend": getattr(backend, "backend_name", "none"),
        "namespace": namespace,
        "upserted": upserted,
        **vector_status,
        "summary": summary_block.get("summary") or "",
        "keywords": summary_block.get("keywords") or [],
        "provider": summary_block.get("provider") or "fallback",
        "model": summary_block.get("model") or "",
    }
    if summary_error:
        result["status"] = "partial"
        result["reason"] = "summary_provider_unavailable"
        result["summary_error"] = summary_error
    return result


async def store_via_seed_documents(bundle: dict[str, Any], items: list[dict[str, Any]]) -> dict[str, Any]:
    backend = build_via_vector_backend()
    namespace = via_namespace_for_bundle(bundle)
    session = bundle.get("session") or {}
    session_key = str(session.get("session_key") or "")
    user_id = int(session.get("user_id") or 0)
    docs = []
    for item in items:
        text = str(item.get("text") or "").strip()
        if not text:
            continue
        docs.append(
            {
                "id": _stable_id(
                    namespace,
                    item.get("memory_kind"),
                    item.get("source_ref"),
                    item.get("memory_key"),
                    text[:160],
                ),
                "text": text[:5000],
                "payload": _seed_payload(namespace, session_key, user_id, item),
            }
        )
    try:
        upserted = await backend.upsert(namespace, docs)
    except Exception as exc:  # noqa: BLE001
        logger.warning("via.vector_memory.seed_upsert_failed", exc_info=True)
        upserted = 0
        status = {
            "ready": False,
            "error": _operation_error("vector_seed_upsert", exc),
            "status": "partial",
            "reason": "vector_seed_upsert_failed",
        }
    else:
        status = _vector_write_status(backend, requested=len(docs), upserted=upserted)
    return {
        "backend": getattr(backend, "backend_name", "none"),
        "namespace": namespace,
        "upserted": upserted,
        **status,
    }
