import type { VkpiProjectStage } from '../vkpiTypes';

export const platformClass: Record<string, string> = {
  YouTube: 'is-youtube',
  Instagram: 'is-instagram',
  TikTok: 'is-tiktok',
  XHS: 'is-xhs',
  Bilibili: 'is-bilibili',
  Facebook: 'is-facebook',
  Reddit: 'is-reddit',
  X: 'is-x',
  Threads: 'is-threads',
  Twitch: 'is-twitch',
  Pinterest: 'is-pinterest',
  Vimeo: 'is-vimeo',
  Discord: 'is-discord',
  Website: 'is-website',
  Weibo: 'is-weibo',
  Douyin: 'is-douyin',
  Zhihu: 'is-zhihu',
  LinkedIn: 'is-linkedin',
  Telegram: 'is-telegram',
  Newsletter: 'is-newsletter',
  Forum: 'is-forum',
  Email: 'is-email',
  Other: 'is-other',
};

export const platformLabels: Record<string, string> = {
  YouTube: 'YouTube',
  Instagram: 'Instagram',
  TikTok: 'TikTok',
  XHS: '小红书',
  Bilibili: 'Bilibili',
  Facebook: 'Facebook',
  Reddit: 'Reddit',
  X: 'X',
  Threads: 'Threads',
  Twitch: 'Twitch',
  Pinterest: 'Pinterest',
  Vimeo: 'Vimeo',
  Discord: 'Discord',
  Website: '官网 / 博客',
  Weibo: '微博',
  Douyin: '抖音',
  Zhihu: '知乎',
  LinkedIn: 'LinkedIn',
  Telegram: 'Telegram',
  Newsletter: 'Newsletter',
  Forum: '论坛',
  Email: '邮件',
  Other: '其他',
};

export const stageLabels: Record<VkpiProjectStage, string> = {
  invited: '已邀请',
  discovery: '发现',
  contacted: '已联系',
  replied: '已回复',
  in_discussion: '沟通中',
  agreed: '已合作',
  shipped: '已发货',
  received: '已到货',
  content_published: '内容已发布',
  published: '已发布',
  measured: '已统计',
  closed: '已关闭',
  stalled: '停滞',
  lost: '已关闭',
  released: '已释放',
  cancelled: '已取消',
};

export const primaryStageFlow: VkpiProjectStage[] = [
  'discovery',
  'contacted',
  'replied',
  'agreed',
  'shipped',
  'received',
  'published',
  'measured',
  'closed',
];

export const creatorPlatformOptions = [
  { value: 'youtube', label: 'YouTube' },
  { value: 'instagram', label: 'Instagram' },
  { value: 'tiktok', label: 'TikTok' },
  { value: 'xhs', label: '小红书' },
  { value: 'bilibili', label: 'Bilibili' },
  { value: 'facebook', label: 'Facebook' },
  { value: 'reddit', label: 'Reddit' },
  { value: 'x', label: 'X' },
  { value: 'threads', label: 'Threads' },
  { value: 'twitch', label: 'Twitch' },
  { value: 'pinterest', label: 'Pinterest' },
  { value: 'vimeo', label: 'Vimeo' },
  { value: 'discord', label: 'Discord 社群' },
  { value: 'website', label: '官网 / 博客' },
  { value: 'weibo', label: '微博' },
  { value: 'douyin', label: '抖音' },
  { value: 'zhihu', label: '知乎' },
  { value: 'linkedin', label: 'LinkedIn' },
  { value: 'telegram', label: 'Telegram' },
  { value: 'newsletter', label: 'Newsletter' },
  { value: 'forum', label: '论坛 / 社区' },
  { value: 'other', label: '其他' },
];

export const linkPlatformOptions = [
  ...creatorPlatformOptions,
  { value: 'shopify', label: 'Shopify' },
  { value: 'amazon', label: 'Amazon' },
];
