"""Schema constants and shared helpers for legacy import staging."""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


ACTIVE_BATCH_STATUSES = ("staging", "staged", "committing", "committed")

PIPELINE_ORDER = [
    "kol_profiles",
    "cooperations",
    "launch_plans",
    "official_content",
    "official_materials",
    "product_costs",
    "risk_watchlist",
    "voc_alerts",
]

PIPELINE_TABLES = {
    "kol_profiles": "vkpi_legacy_kol_profiles_staging",
    "cooperations": "vkpi_legacy_cooperations_staging",
    "launch_plans": "vkpi_legacy_launch_plans_staging",
    "official_content": "vkpi_legacy_official_content_staging",
    "official_materials": "vkpi_legacy_official_materials_staging",
    "product_costs": "vkpi_legacy_product_costs_staging",
    "risk_watchlist": "vkpi_legacy_risk_watchlist_staging",
    "voc_alerts": "vkpi_legacy_voc_alerts_staging",
}

STAGING_COLUMNS = {
    "kol_profiles": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "platform",
        "normalized_platform",
        "handle",
        "normalized_handle",
        "dedup_key",
        "display_name",
        "country",
        "region",
        "category",
        "email",
        "phone",
        "address",
        "notes",
        "contact_missing",
        "contact_visibility_level",
        "contains_pii",
        "duplicate_in_batch",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "cooperations": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "platform",
        "normalized_platform",
        "handle",
        "normalized_handle",
        "dedup_key",
        "display_name",
        "product",
        "project",
        "status",
        "cooperation_date",
        "cost_amount",
        "cost_currency",
        "content_link",
        "result",
        "notes",
        "unmatched_kol_review",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "launch_plans": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "launch_name",
        "product_sku",
        "product_name",
        "category_primary",
        "category_secondary",
        "launch_date",
        "target_region",
        "target_platforms_json",
        "campaign_owner",
        "official_material_ref",
        "kol_plan_ref",
        "product_page_url",
        "status",
        "notes",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "official_content": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "official_account",
        "platform",
        "normalized_platform",
        "publish_date",
        "content_type",
        "title",
        "product",
        "link",
        "status",
        "owner",
        "notes",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "official_materials": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "launch_ref",
        "product_sku",
        "product_name",
        "owner",
        "production_status",
        "project",
        "content_type",
        "content_description",
        "reference_doc",
        "content_format",
        "request_date",
        "target_delivery_date",
        "asset_link",
        "size_spec",
        "publish_status",
        "product_publish_date",
        "production_team",
        "budget_amount",
        "budget_currency",
        "official_usage_ref",
        "parent_ref",
        "notes",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "product_costs": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "sku",
        "product_name",
        "cost",
        "currency",
        "region",
        "effective_date",
        "notes",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "risk_watchlist": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "platform",
        "normalized_platform",
        "handle",
        "normalized_handle",
        "dedup_key",
        "display_name",
        "risk_type",
        "risk_reason",
        "severity",
        "evidence",
        "status",
        "notes",
        "risk_only",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
    "voc_alerts": [
        "import_batch_id",
        "row_uid",
        "source_sheet",
        "source_row",
        "platform",
        "normalized_platform",
        "product",
        "issue_type",
        "sentiment",
        "content",
        "link",
        "evidence",
        "issue_date",
        "severity",
        "status",
        "owner",
        "notes",
        "review_status",
        "review_reason_json",
        "import_action",
        "row_hash",
        "raw_row_json",
        "validation_json",
    ],
}

PIPELINE_DEFAULTS = {
    "kol_profiles": {
        "platform": "",
        "normalized_platform": "",
        "handle": "",
        "normalized_handle": "",
        "dedup_key": "",
        "display_name": "",
        "country": "",
        "region": "",
        "category": "",
        "email": "",
        "phone": "",
        "address": "",
        "notes": "",
        "contact_missing": False,
        "contact_visibility_level": "restricted",
        "contains_pii": True,
        "duplicate_in_batch": False,
    },
    "cooperations": {
        "platform": "",
        "normalized_platform": "",
        "handle": "",
        "normalized_handle": "",
        "dedup_key": "",
        "display_name": "",
        "product": "",
        "project": "",
        "status": "",
        "cost_currency": "",
        "content_link": "",
        "result": "",
        "notes": "",
        "unmatched_kol_review": False,
    },
    "launch_plans": {
        "launch_name": "",
        "product_sku": "",
        "product_name": "",
        "category_primary": "",
        "category_secondary": "",
        "target_region": "",
        "target_platforms_json": "[]",
        "campaign_owner": "",
        "official_material_ref": "",
        "kol_plan_ref": "",
        "product_page_url": "",
        "status": "planned",
        "notes": "",
    },
    "official_content": {
        "official_account": "",
        "platform": "",
        "normalized_platform": "",
        "content_type": "",
        "title": "",
        "product": "",
        "link": "",
        "status": "",
        "owner": "",
        "notes": "",
    },
    "official_materials": {
        "launch_ref": "",
        "product_sku": "",
        "product_name": "",
        "owner": "",
        "production_status": "",
        "project": "",
        "content_type": "",
        "content_description": "",
        "reference_doc": "",
        "content_format": "",
        "asset_link": "",
        "size_spec": "",
        "publish_status": "",
        "production_team": "",
        "budget_currency": "",
        "official_usage_ref": "",
        "parent_ref": "",
        "notes": "",
    },
    "product_costs": {
        "sku": "",
        "product_name": "",
        "currency": "",
        "region": "",
        "notes": "",
    },
    "risk_watchlist": {
        "platform": "",
        "normalized_platform": "",
        "handle": "",
        "normalized_handle": "",
        "dedup_key": "",
        "display_name": "",
        "risk_type": "",
        "risk_reason": "",
        "severity": "medium",
        "evidence": "",
        "status": "open",
        "notes": "",
        "risk_only": True,
    },
    "voc_alerts": {
        "platform": "",
        "normalized_platform": "",
        "product": "",
        "issue_type": "",
        "sentiment": "",
        "content": "",
        "link": "",
        "evidence": "",
        "severity": "medium",
        "status": "open",
        "owner": "",
        "notes": "",
    },
}


@dataclass
class StageRecord:
    pipeline: str
    source_sheet: str
    source_row: int
    raw: dict[str, str]
    values: dict[str, Any]
    review_reasons: list[str] = field(default_factory=list)

    @property
    def table(self) -> str:
        return PIPELINE_TABLES[self.pipeline]


def json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)


def file_sha256(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).expanduser().open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()
