#!/usr/bin/env python3
"""No-provider smoke test for 100-user KOL smart-search queue ordering.

This intentionally does not insert into real apify_jobs. It uses a PostgreSQL
temporary table with the same ordered claim contract as the worker:
ORDER BY created_at, id FOR UPDATE SKIP LOCKED.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover - local dependency guard.
    load_dotenv = None  # type: ignore[assignment]

import psycopg  # noqa: E402
from psycopg.rows import dict_row  # noqa: E402

REPORT_PATH = ROOT / "runtime" / "kol-smart-queue-load-smoke-latest.json"
METHOD = "kol_smart_queue_load_smoke_v1"


def _load_env() -> None:
    if load_dotenv is not None:
        load_dotenv(ROOT / ".env")
        return
    env_path = ROOT / ".env"
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def _database_url() -> str:
    return os.environ.get("DATABASE_URL", "").strip() or "postgresql://postgres@127.0.0.1:54329/viltrox2"


def _git_value(*args: str) -> str:
    try:
        return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return ""


def _scalar(conn: psycopg.Connection[Any], sql: str) -> int:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(sql)
        row = cur.fetchone() or {}
    value = next(iter(row.values()), 0) if row else 0
    return int(value or 0)


def _v6_fit_checksum(conn: psycopg.Connection[Any]) -> str:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT md5(
              COALESCE(
                string_agg(
                  id::text || ':' || COALESCE(viltrox_fit_score::text, 'NULL') || ':' || COALESCE(viltrox_fit_reason, ''),
                  ',' ORDER BY id
                ),
                ''
              )
            ) AS checksum
            FROM vkpi_kol_pool
            """
        )
        row = cur.fetchone() or {}
    return str(row.get("checksum") or "")


def _payload(user_index: int, *, query: str) -> dict[str, Any]:
    return {
        "target_type": "search_session",
        "target_id": f"smoke-{user_index}",
        "derive_method": "kol_smart_search_profile_advance",
        "search_session_id": user_index,
        "query_text": query,
        "product_sku": "smoke",
        "candidate_limit": 100,
        "limit": 30,
        "creator_quota": 15,
        "reviewer_quota": 15,
        "ratio_policy": "soft",
        "mixed_policy": "dominant",
        "dedupe": True,
        "vector_weight": 0.7,
        "type_weight": 0.3,
        "type_boost_enabled": True,
        "include_new_discovery": True,
        "new_discovery_limit": 15,
        "new_discovery_per_platform_limit": 15,
        "platform": "",
        "market": "",
        "advance_limit": 15,
        "max_posts": 12,
        "advance_mode": "account_deep",
        "representative_video_limit": 1,
        "item_types": ["new_creator", "existing_kol", "recall_candidate"],
        "include_completed": False,
        "prompt": f"queue load smoke #{user_index}",
        "summary": f"queue load smoke #{user_index}",
        "triggered_by_user_id": None,
        "viltrox_fit_score_untouched": True,
        "smoke_user_index": user_index,
    }


def _setup_temp_queue(cur: psycopg.Cursor[Any]) -> None:
    cur.execute(
        """
        CREATE TEMP TABLE tmp_kol_smart_queue_load_jobs (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          job_type text NOT NULL,
          payload jsonb NOT NULL,
          status text NOT NULL DEFAULT 'queued',
          user_index integer NOT NULL,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL
        ) ON COMMIT DROP
        """
    )
    cur.execute(
        """
        CREATE INDEX tmp_kol_smart_queue_load_jobs_status_created_idx
        ON tmp_kol_smart_queue_load_jobs(status, created_at, id)
        """
    )


def _insert_temp_jobs(cur: psycopg.Cursor[Any], *, users: int, query: str) -> None:
    now = datetime.now(timezone.utc)
    rows = []
    for user_index in range(1, users + 1):
        created_at = now + timedelta(microseconds=user_index)
        rows.append(
            (
                "smart_search_profile_advance",
                json.dumps(_payload(user_index, query=query), ensure_ascii=False, sort_keys=True),
                "queued",
                user_index,
                created_at,
                created_at,
            )
        )
    cur.executemany(
        """
        INSERT INTO tmp_kol_smart_queue_load_jobs
          (job_type, payload, status, user_index, created_at, updated_at)
        VALUES (%s, %s::jsonb, %s, %s, %s, %s)
        """,
        rows,
    )


def _claim_one(cur: psycopg.Cursor[Any]) -> dict[str, Any] | None:
    cur.execute(
        """
        WITH next_job AS (
          SELECT id
          FROM tmp_kol_smart_queue_load_jobs
          WHERE status = 'queued'
          ORDER BY created_at, id
          FOR UPDATE SKIP LOCKED
          LIMIT 1
        )
        UPDATE tmp_kol_smart_queue_load_jobs job
           SET status='running', updated_at=clock_timestamp()
          FROM next_job
         WHERE job.id=next_job.id
        RETURNING job.id, job.job_type, job.payload, job.status, job.user_index, job.created_at, job.updated_at
        """
    )
    row = cur.fetchone()
    return dict(row) if row else None


def _finish_batch(cur: psycopg.Cursor[Any], ids: list[int]) -> None:
    if not ids:
        return
    cur.execute(
        """
        UPDATE tmp_kol_smart_queue_load_jobs
           SET status='done', updated_at=clock_timestamp()
         WHERE id = ANY(%s::int[])
        """,
        (ids,),
    )


def run_smoke(*, users: int, batch_size: int, query: str) -> dict[str, Any]:
    if users < 1:
        raise ValueError("--users must be at least 1")
    if batch_size < 1:
        raise ValueError("--batch-size must be at least 1")
    _load_env()
    started = time.perf_counter()
    conn = psycopg.connect(_database_url(), row_factory=dict_row)
    try:
        before_apify_jobs = _scalar(conn, "SELECT count(*) FROM apify_jobs")
        before_v6_checksum = _v6_fit_checksum(conn)
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute("SET LOCAL statement_timeout = '30s'")
            _setup_temp_queue(cur)
            _insert_temp_jobs(cur, users=users, query=query)
            cur.execute("SELECT count(*) AS count FROM tmp_kol_smart_queue_load_jobs")
            inserted = int((cur.fetchone() or {}).get("count") or 0)

            claimed: list[dict[str, Any]] = []
            while len(claimed) < users:
                batch_ids: list[int] = []
                for _ in range(batch_size):
                    row = _claim_one(cur)
                    if row is None:
                        break
                    claimed.append(row)
                    batch_ids.append(int(row["id"]))
                if not batch_ids:
                    break
                _finish_batch(cur, batch_ids)

            cur.execute(
                """
                SELECT status, count(*) AS count
                FROM tmp_kol_smart_queue_load_jobs
                GROUP BY status
                ORDER BY status
                """
            )
            temp_status_counts = [dict(row) for row in cur.fetchall()]
        after_apify_jobs = _scalar(conn, "SELECT count(*) FROM apify_jobs")
        after_v6_checksum = _v6_fit_checksum(conn)
    finally:
        conn.rollback()
        conn.close()

    claimed_user_indexes = [int(row["user_index"]) for row in claimed]
    expected_order = list(range(1, users + 1))
    ordered = claimed_user_indexes == expected_order
    elapsed_ms = round((time.perf_counter() - started) * 1000, 2)
    persistent_write = before_apify_jobs != after_apify_jobs
    v6_fit_changed = before_v6_checksum != after_v6_checksum
    status = "pass" if inserted == users and len(claimed) == users and ordered and not persistent_write and not v6_fit_changed else "fail"
    return {
        "status": status,
        "method": METHOD,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "branch": _git_value("rev-parse", "--abbrev-ref", "HEAD"),
        "short_sha": _git_value("rev-parse", "--short", "HEAD"),
        "mode": "temporary_table_no_provider_no_worker",
        "job_type": "smart_search_profile_advance",
        "derive_method": "kol_smart_search_profile_advance",
        "claim_contract": "ORDER BY created_at, id FOR UPDATE SKIP LOCKED",
        "users": users,
        "batch_size": batch_size,
        "inserted": inserted,
        "claimed": len(claimed),
        "ordered": ordered,
        "first_claimed_user_indexes": claimed_user_indexes[:10],
        "last_claimed_user_indexes": claimed_user_indexes[-10:],
        "temp_status_counts": temp_status_counts,
        "elapsed_ms": elapsed_ms,
        "provider_calls_performed": False,
        "worker_visible": False,
        "persistent_write": persistent_write,
        "apify_jobs_before": before_apify_jobs,
        "apify_jobs_after": after_apify_jobs,
        "viltrox_fit_score_changed": v6_fit_changed,
        "viltrox_fit_score_checksum_before": before_v6_checksum,
        "viltrox_fit_score_checksum_after": after_v6_checksum,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Smoke test KOL smart-search queue ordering with temporary rows only.")
    parser.add_argument("--users", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=10)
    parser.add_argument("--query", default="smoke queue load · flash compatible creators")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    report = run_smoke(users=int(args.users), batch_size=int(args.batch_size), query=str(args.query or ""))
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")
    print(f"status={report['status']}")
    print(f"users={report['users']} inserted={report['inserted']} claimed={report['claimed']} ordered={report['ordered']}")
    print(f"provider_calls_performed={report['provider_calls_performed']} worker_visible={report['worker_visible']} persistent_write={report['persistent_write']}")
    print(f"viltrox_fit_score_changed={report['viltrox_fit_score_changed']}")
    print(f"elapsed_ms={report['elapsed_ms']}")
    print(f"report={REPORT_PATH}")
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True, default=str))
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
