"""Settings domain facade."""

from app.domains.settings.use_cases import (
    budget_settings,
    can_view_all,
    comment_alert_settings,
    control_status,
    feature_flags,
    is_manager_staff,
    notifications,
    notifications_list,
    platform_crawl,
    preference_settings,
    preference_settings_list,
    provider_probe,
    provider_statuses,
    update_budget_settings,
    update_comment_alert_settings,
    update_feature_flags,
    update_notifications,
    update_platform_crawl,
    update_preference_settings,
)

__all__ = [
    "budget_settings",
    "can_view_all",
    "comment_alert_settings",
    "control_status",
    "feature_flags",
    "is_manager_staff",
    "notifications",
    "notifications_list",
    "platform_crawl",
    "preference_settings",
    "preference_settings_list",
    "provider_probe",
    "provider_statuses",
    "update_budget_settings",
    "update_comment_alert_settings",
    "update_feature_flags",
    "update_notifications",
    "update_platform_crawl",
    "update_preference_settings",
]
